\ 07-math.fs
\ PDR-16 math library core words.

\ BEGIN GENERATED MATH TABLES
\ Generated by V5/Simulator/generate_math_tables.py.
\ Quarter-wave sine plus interpolation tables for the math library.
\ Sine uses 256 entries over 0 <= binian < 16384.
\ LOG2/EXP2/ATAN tables use 256 segments with 16 fractional steps each.

CREATE SINQ-TABLE
>BASE HEX
   0 ,   C9 ,  192 ,  25B ,  324 ,  3ED ,  4B6 ,  57F ,
 648 ,  711 ,  7D9 ,  8A2 ,  96A ,  A33 ,  AFB ,  BC4 ,
 C8C ,  D54 ,  E1C ,  EE3 ,  FAB , 1072 , 113A , 1201 ,
12C8 , 138F , 1455 , 151C , 15E2 , 16A8 , 176E , 1833 ,
18F9 , 19BE , 1A82 , 1B47 , 1C0B , 1CCF , 1D93 , 1E57 ,
1F1A , 1FDD , 209F , 2161 , 2223 , 22E5 , 23A6 , 2467 ,
2528 , 25E8 , 26A8 , 2767 , 2826 , 28E5 , 29A3 , 2A61 ,
2B1F , 2BDC , 2C99 , 2D55 , 2E11 , 2ECC , 2F87 , 3041 ,

30FB , 31B5 , 326E , 3326 , 33DF , 3496 , 354D , 3604 ,
36BA , 376F , 3824 , 38D9 , 398C , 3A40 , 3AF2 , 3BA5 ,
3C56 , 3D07 , 3DB8 , 3E68 , 3F17 , 3FC5 , 4073 , 4121 ,
41CE , 427A , 4325 , 43D0 , 447A , 4524 , 45CD , 4675 ,
471C , 47C3 , 4869 , 490F , 49B4 , 4A58 , 4AFB , 4B9D ,
4C3F , 4CE0 , 4D81 , 4E20 , 4EBF , 4F5D , 4FFB , 5097 ,
5133 , 51CE , 5268 , 5302 , 539B , 5432 , 54C9 , 5560 ,
55F5 , 568A , 571D , 57B0 , 5842 , 58D3 , 5964 , 59F3 ,

5A82 , 5B0F , 5B9C , 5C28 , 5CB3 , 5D3E , 5DC7 , 5E4F ,
5ED7 , 5F5D , 5FE3 , 6068 , 60EB , 616E , 61F0 , 6271 ,
62F1 , 6370 , 63EE , 646C , 64E8 , 6563 , 65DD , 6656 ,
66CF , 6746 , 67BC , 6832 , 68A6 , 6919 , 698B , 69FD ,
6A6D , 6ADC , 6B4A , 6BB7 , 6C23 , 6C8E , 6CF8 , 6D61 ,
6DC9 , 6E30 , 6E96 , 6EFB , 6F5E , 6FC1 , 7022 , 7083 ,
70E2 , 7140 , 719D , 71F9 , 7254 , 72AE , 7307 , 735E ,
73B5 , 740A , 745F , 74B2 , 7504 , 7555 , 75A5 , 75F3 ,

7641 , 768D , 76D8 , 7722 , 776B , 77B3 , 77FA , 783F ,
7884 , 78C7 , 7909 , 794A , 7989 , 79C8 , 7A05 , 7A41 ,
7A7C , 7AB6 , 7AEE , 7B26 , 7B5C , 7B91 , 7BC5 , 7BF8 ,
7C29 , 7C59 , 7C88 , 7CB6 , 7CE3 , 7D0E , 7D39 , 7D62 ,
7D89 , 7DB0 , 7DD5 , 7DFA , 7E1D , 7E3E , 7E5F , 7E7E ,
7E9C , 7EB9 , 7ED5 , 7EEF , 7F09 , 7F21 , 7F37 , 7F4D ,
7F61 , 7F74 , 7F86 , 7F97 , 7FA6 , 7FB4 , 7FC1 , 7FCD ,
7FD8 , 7FE1 , 7FE9 , 7FF0 , 7FF5 , 7FF9 , 7FFD , 7FFE ,

BASE>

PRIVATE

CREATE POW2-TABLE
>BASE HEX
    1 ,     2 ,     4 ,     8 ,    10 ,    20 ,    40 ,    80 ,
  100 ,   200 ,   400 ,   800 ,  1000 ,  2000 ,  4000 , -8000 ,
BASE>

PRIVATE

CREATE LOG2I-TABLE
>BASE HEX
    0 ,  1000 ,  2000 ,  3000 ,  4000 ,  5000 ,  6000 ,  7000 ,
-8000 , -7000 , -6000 , -5000 , -4000 , -3000 , -2000 , -1000 ,
BASE>

PRIVATE

CREATE LOG2F-TABLE
>BASE HEX
   0 ,   17 ,   2E ,   45 ,   5C ,   72 ,   89 ,   9F ,
  B6 ,   CC ,   E2 ,   F9 ,  10F ,  125 ,  13B ,  150 ,
 166 ,  17C ,  192 ,  1A7 ,  1BD ,  1D2 ,  1E7 ,  1FC ,
 212 ,  227 ,  23C ,  251 ,  265 ,  27A ,  28F ,  2A3 ,
 2B8 ,  2CC ,  2E1 ,  2F5 ,  30A ,  31E ,  332 ,  346 ,
 35A ,  36E ,  382 ,  396 ,  3A9 ,  3BD ,  3D1 ,  3E4 ,
 3F8 ,  40B ,  41E ,  432 ,  445 ,  458 ,  46B ,  47E ,
 491 ,  4A4 ,  4B7 ,  4CA ,  4DC ,  4EF ,  502 ,  514 ,

 527 ,  539 ,  54B ,  55E ,  570 ,  582 ,  594 ,  5A6 ,
 5B9 ,  5CB ,  5DC ,  5EE ,  600 ,  612 ,  624 ,  635 ,
 647 ,  658 ,  66A ,  67B ,  68D ,  69E ,  6B0 ,  6C1 ,
 6D2 ,  6E3 ,  6F4 ,  705 ,  716 ,  727 ,  738 ,  749 ,
 75A ,  76B ,  77B ,  78C ,  79D ,  7AD ,  7BE ,  7CE ,
 7DF ,  7EF ,  7FF ,  810 ,  820 ,  830 ,  840 ,  850 ,
 861 ,  871 ,  881 ,  890 ,  8A0 ,  8B0 ,  8C0 ,  8D0 ,
 8E0 ,  8EF ,  8FF ,  90F ,  91E ,  92E ,  93D ,  94D ,

 95C ,  96B ,  97B ,  98A ,  999 ,  9A8 ,  9B8 ,  9C7 ,
 9D6 ,  9E5 ,  9F4 ,  A03 ,  A12 ,  A21 ,  A30 ,  A3E ,
 A4D ,  A5C ,  A6B ,  A79 ,  A88 ,  A97 ,  AA5 ,  AB4 ,
 AC2 ,  AD1 ,  ADF ,  AEE ,  AFC ,  B0A ,  B19 ,  B27 ,
 B35 ,  B43 ,  B51 ,  B5F ,  B6E ,  B7C ,  B8A ,  B98 ,
 BA6 ,  BB3 ,  BC1 ,  BCF ,  BDD ,  BEB ,  BF9 ,  C06 ,
 C14 ,  C22 ,  C2F ,  C3D ,  C4A ,  C58 ,  C66 ,  C73 ,
 C80 ,  C8E ,  C9B ,  CA9 ,  CB6 ,  CC3 ,  CD0 ,  CDE ,

 CEB ,  CF8 ,  D05 ,  D12 ,  D1F ,  D2D ,  D3A ,  D47 ,
 D54 ,  D60 ,  D6D ,  D7A ,  D87 ,  D94 ,  DA1 ,  DAE ,
 DBA ,  DC7 ,  DD4 ,  DE0 ,  DED ,  DFA ,  E06 ,  E13 ,
 E1F ,  E2C ,  E38 ,  E45 ,  E51 ,  E5E ,  E6A ,  E76 ,
 E83 ,  E8F ,  E9B ,  EA7 ,  EB4 ,  EC0 ,  ECC ,  ED8 ,
 EE4 ,  EF0 ,  EFC ,  F09 ,  F15 ,  F21 ,  F2D ,  F38 ,
 F44 ,  F50 ,  F5C ,  F68 ,  F74 ,  F80 ,  F8B ,  F97 ,
 FA3 ,  FAF ,  FBA ,  FC6 ,  FD2 ,  FDD ,  FE9 ,  FF4 ,

1000 ,
BASE>

PRIVATE

CREATE LOG2D-TABLE
>BASE HEX
17 , 17 , 17 , 17 , 16 , 17 , 16 , 17 ,
16 , 16 , 17 , 16 , 16 , 16 , 15 , 16 ,
16 , 16 , 15 , 16 , 15 , 15 , 15 , 16 ,
15 , 15 , 15 , 14 , 15 , 15 , 14 , 15 ,
14 , 15 , 14 , 15 , 14 , 14 , 14 , 14 ,
14 , 14 , 14 , 13 , 14 , 14 , 13 , 14 ,
13 , 13 , 14 , 13 , 13 , 13 , 13 , 13 ,
13 , 13 , 13 , 12 , 13 , 13 , 12 , 13 ,

12 , 12 , 13 , 12 , 12 , 12 , 12 , 13 ,
12 , 11 , 12 , 12 , 12 , 12 , 11 , 12 ,
11 , 12 , 11 , 12 , 11 , 12 , 11 , 11 ,
11 , 11 , 11 , 11 , 11 , 11 , 11 , 11 ,
11 , 10 , 11 , 11 , 10 , 11 , 10 , 11 ,
10 , 10 , 11 , 10 , 10 , 10 , 10 , 11 ,
10 , 10 ,  F , 10 , 10 , 10 , 10 , 10 ,
 F , 10 , 10 ,  F , 10 ,  F , 10 ,  F ,

 F , 10 ,  F ,  F ,  F , 10 ,  F ,  F ,
 F ,  F ,  F ,  F ,  F ,  F ,  E ,  F ,
 F ,  F ,  E ,  F ,  F ,  E ,  F ,  E ,
 F ,  E ,  F ,  E ,  E ,  F ,  E ,  E ,
 E ,  E ,  E ,  F ,  E ,  E ,  E ,  E ,
 D ,  E ,  E ,  E ,  E ,  E ,  D ,  E ,
 E ,  D ,  E ,  D ,  E ,  E ,  D ,  D ,
 E ,  D ,  E ,  D ,  D ,  D ,  E ,  D ,

 D ,  D ,  D ,  D ,  E ,  D ,  D ,  D ,
 C ,  D ,  D ,  D ,  D ,  D ,  D ,  C ,
 D ,  D ,  C ,  D ,  D ,  C ,  D ,  C ,
 D ,  C ,  D ,  C ,  D ,  C ,  C ,  D ,
 C ,  C ,  C ,  D ,  C ,  C ,  C ,  C ,
 C ,  C ,  D ,  C ,  C ,  C ,  B ,  C ,
 C ,  C ,  C ,  C ,  C ,  B ,  C ,  C ,
 C ,  B ,  C ,  C ,  B ,  C ,  B ,  C ,

BASE>

PRIVATE

CREATE EXP2F-TABLE
>BASE HEX
1000 , 100B , 1016 , 1021 , 102D , 1038 , 1043 , 104E ,
105A , 1065 , 1070 , 107C , 1087 , 1093 , 109E , 10AA ,
10B5 , 10C1 , 10CD , 10D8 , 10E4 , 10F0 , 10FB , 1107 ,
1113 , 111F , 112B , 1137 , 1143 , 114F , 115B , 1167 ,
1173 , 117F , 118B , 1197 , 11A3 , 11B0 , 11BC , 11C8 ,
11D5 , 11E1 , 11ED , 11FA , 1206 , 1213 , 121F , 122C ,
1238 , 1245 , 1252 , 125F , 126B , 1278 , 1285 , 1292 ,
129F , 12AC , 12B8 , 12C5 , 12D3 , 12E0 , 12ED , 12FA ,

1307 , 1314 , 1321 , 132F , 133C , 1349 , 1357 , 1364 ,
1372 , 137F , 138D , 139A , 13A8 , 13B5 , 13C3 , 13D1 ,
13DF , 13EC , 13FA , 1408 , 1416 , 1424 , 1432 , 1440 ,
144E , 145C , 146A , 1478 , 1487 , 1495 , 14A3 , 14B1 ,
14C0 , 14CE , 14DD , 14EB , 14FA , 1508 , 1517 , 1525 ,
1534 , 1543 , 1552 , 1560 , 156F , 157E , 158D , 159C ,
15AB , 15BA , 15C9 , 15D8 , 15E7 , 15F7 , 1606 , 1615 ,
1624 , 1634 , 1643 , 1653 , 1662 , 1672 , 1681 , 1691 ,

16A1 , 16B0 , 16C0 , 16D0 , 16E0 , 16F0 , 16FF , 170F ,
171F , 1730 , 1740 , 1750 , 1760 , 1770 , 1780 , 1791 ,
17A1 , 17B1 , 17C2 , 17D2 , 17E3 , 17F4 , 1804 , 1815 ,
1826 , 1836 , 1847 , 1858 , 1869 , 187A , 188B , 189C ,
18AD , 18BE , 18CF , 18E0 , 18F2 , 1903 , 1914 , 1926 ,
1937 , 1949 , 195A , 196C , 197E , 198F , 19A1 , 19B3 ,
19C5 , 19D6 , 19E8 , 19FA , 1A0C , 1A1E , 1A31 , 1A43 ,
1A55 , 1A67 , 1A7A , 1A8C , 1A9E , 1AB1 , 1AC3 , 1AD6 ,

1AE9 , 1AFB , 1B0E , 1B21 , 1B34 , 1B47 , 1B59 , 1B6C ,
1B7F , 1B93 , 1BA6 , 1BB9 , 1BCC , 1BDF , 1BF3 , 1C06 ,
1C1A , 1C2D , 1C41 , 1C54 , 1C68 , 1C7C , 1C8F , 1CA3 ,
1CB7 , 1CCB , 1CDF , 1CF3 , 1D07 , 1D1B , 1D30 , 1D44 ,
1D58 , 1D6C , 1D81 , 1D95 , 1DAA , 1DBE , 1DD3 , 1DE8 ,
1DFD , 1E11 , 1E26 , 1E3B , 1E50 , 1E65 , 1E7A , 1E8F ,
1EA5 , 1EBA , 1ECF , 1EE5 , 1EFA , 1F10 , 1F25 , 1F3B ,
1F50 , 1F66 , 1F7C , 1F92 , 1FA8 , 1FBE , 1FD4 , 1FEA ,

2000 ,
BASE>

PRIVATE

CREATE EXP2D-TABLE
>BASE HEX
 B ,  B ,  B ,  C ,  B ,  B ,  B ,  C ,
 B ,  B ,  C ,  B ,  C ,  B ,  C ,  B ,
 C ,  C ,  B ,  C ,  C ,  B ,  C ,  C ,
 C ,  C ,  C ,  C ,  C ,  C ,  C ,  C ,
 C ,  C ,  C ,  C ,  D ,  C ,  C ,  D ,
 C ,  C ,  D ,  C ,  D ,  C ,  D ,  C ,
 D ,  D ,  D ,  C ,  D ,  D ,  D ,  D ,
 D ,  C ,  D ,  E ,  D ,  D ,  D ,  D ,

 D ,  D ,  E ,  D ,  D ,  E ,  D ,  E ,
 D ,  E ,  D ,  E ,  D ,  E ,  E ,  E ,
 D ,  E ,  E ,  E ,  E ,  E ,  E ,  E ,
 E ,  E ,  E ,  F ,  E ,  E ,  E ,  F ,
 E ,  F ,  E ,  F ,  E ,  F ,  E ,  F ,
 F ,  F ,  E ,  F ,  F ,  F ,  F ,  F ,
 F ,  F ,  F ,  F , 10 ,  F ,  F ,  F ,
10 ,  F , 10 ,  F , 10 ,  F , 10 , 10 ,

 F , 10 , 10 , 10 , 10 ,  F , 10 , 10 ,
11 , 10 , 10 , 10 , 10 , 10 , 11 , 10 ,
10 , 11 , 10 , 11 , 11 , 10 , 11 , 11 ,
10 , 11 , 11 , 11 , 11 , 11 , 11 , 11 ,
11 , 11 , 11 , 12 , 11 , 11 , 12 , 11 ,
12 , 11 , 12 , 12 , 11 , 12 , 12 , 12 ,
11 , 12 , 12 , 12 , 12 , 13 , 12 , 12 ,
12 , 13 , 12 , 12 , 13 , 12 , 13 , 13 ,

12 , 13 , 13 , 13 , 13 , 12 , 13 , 13 ,
14 , 13 , 13 , 13 , 13 , 14 , 13 , 14 ,
13 , 14 , 13 , 14 , 14 , 13 , 14 , 14 ,
14 , 14 , 14 , 14 , 14 , 15 , 14 , 14 ,
14 , 15 , 14 , 15 , 14 , 15 , 15 , 15 ,
14 , 15 , 15 , 15 , 15 , 15 , 15 , 16 ,
15 , 15 , 16 , 15 , 16 , 15 , 16 , 15 ,
16 , 16 , 16 , 16 , 16 , 16 , 16 , 16 ,

BASE>

PRIVATE

CREATE ATANF-TABLE
>BASE HEX
   0 ,   29 ,   51 ,   7A ,   A3 ,   CC ,   F4 ,  11D ,
 146 ,  16F ,  197 ,  1C0 ,  1E9 ,  211 ,  23A ,  262 ,
 28B ,  2B4 ,  2DC ,  305 ,  32D ,  356 ,  37E ,  3A7 ,
 3CF ,  3F7 ,  420 ,  448 ,  470 ,  499 ,  4C1 ,  4E9 ,
 511 ,  539 ,  561 ,  589 ,  5B1 ,  5D9 ,  601 ,  629 ,
 651 ,  678 ,  6A0 ,  6C8 ,  6EF ,  717 ,  73E ,  766 ,
 78D ,  7B5 ,  7DC ,  803 ,  82A ,  851 ,  878 ,  89F ,
 8C6 ,  8ED ,  914 ,  93B ,  961 ,  988 ,  9AE ,  9D5 ,

 9FB ,  A22 ,  A48 ,  A6E ,  A94 ,  ABA ,  AE0 ,  B06 ,
 B2C ,  B51 ,  B77 ,  B9D ,  BC2 ,  BE7 ,  C0D ,  C32 ,
 C57 ,  C7C ,  CA1 ,  CC6 ,  CEB ,  D10 ,  D34 ,  D59 ,
 D7D ,  DA2 ,  DC6 ,  DEA ,  E0F ,  E33 ,  E56 ,  E7A ,
 E9E ,  EC2 ,  EE5 ,  F09 ,  F2C ,  F50 ,  F73 ,  F96 ,
 FB9 ,  FDC ,  FFF , 1021 , 1044 , 1067 , 1089 , 10AB ,
10CE , 10F0 , 1112 , 1134 , 1156 , 1177 , 1199 , 11BB ,
11DC , 11FD , 121F , 1240 , 1261 , 1282 , 12A3 , 12C3 ,

12E4 , 1305 , 1325 , 1345 , 1366 , 1386 , 13A6 , 13C6 ,
13E6 , 1405 , 1425 , 1444 , 1464 , 1483 , 14A2 , 14C1 ,
14E0 , 14FF , 151E , 153D , 155B , 157A , 1598 , 15B7 ,
15D5 , 15F3 , 1611 , 162F , 164C , 166A , 1688 , 16A5 ,
16C2 , 16E0 , 16FD , 171A , 1737 , 1754 , 1770 , 178D ,
17AA , 17C6 , 17E2 , 17FE , 181B , 1837 , 1853 , 186E ,
188A , 18A6 , 18C1 , 18DD , 18F8 , 1913 , 192E , 1949 ,
1964 , 197F , 199A , 19B4 , 19CF , 19E9 , 1A04 , 1A1E ,

1A38 , 1A52 , 1A6C , 1A86 , 1A9F , 1AB9 , 1AD3 , 1AEC ,
1B05 , 1B1F , 1B38 , 1B51 , 1B6A , 1B83 , 1B9C , 1BB4 ,
1BCD , 1BE5 , 1BFE , 1C16 , 1C2E , 1C46 , 1C5E , 1C76 ,
1C8E , 1CA6 , 1CBE , 1CD5 , 1CED , 1D04 , 1D1B , 1D33 ,
1D4A , 1D61 , 1D78 , 1D8E , 1DA5 , 1DBC , 1DD3 , 1DE9 ,
1DFF , 1E16 , 1E2C , 1E42 , 1E58 , 1E6E , 1E84 , 1E9A ,
1EB0 , 1EC5 , 1EDB , 1EF0 , 1F06 , 1F1B , 1F30 , 1F45 ,
1F5A , 1F6F , 1F84 , 1F99 , 1FAE , 1FC3 , 1FD7 , 1FEC ,

2000 ,
BASE>

PRIVATE

CREATE ATAND-TABLE
>BASE HEX
29 , 28 , 29 , 29 , 29 , 28 , 29 , 29 ,
29 , 28 , 29 , 29 , 28 , 29 , 28 , 29 ,
29 , 28 , 29 , 28 , 29 , 28 , 29 , 28 ,
28 , 29 , 28 , 28 , 29 , 28 , 28 , 28 ,
28 , 28 , 28 , 28 , 28 , 28 , 28 , 28 ,
27 , 28 , 28 , 27 , 28 , 27 , 28 , 27 ,
28 , 27 , 27 , 27 , 27 , 27 , 27 , 27 ,
27 , 27 , 27 , 26 , 27 , 26 , 27 , 26 ,

27 , 26 , 26 , 26 , 26 , 26 , 26 , 26 ,
25 , 26 , 26 , 25 , 25 , 26 , 25 , 25 ,
25 , 25 , 25 , 25 , 25 , 24 , 25 , 24 ,
25 , 24 , 24 , 25 , 24 , 23 , 24 , 24 ,
24 , 23 , 24 , 23 , 24 , 23 , 23 , 23 ,
23 , 23 , 22 , 23 , 23 , 22 , 22 , 23 ,
22 , 22 , 22 , 22 , 21 , 22 , 22 , 21 ,
21 , 22 , 21 , 21 , 21 , 21 , 20 , 21 ,

21 , 20 , 20 , 21 , 20 , 20 , 20 , 20 ,
1F , 20 , 1F , 20 , 1F , 1F , 1F , 1F ,
1F , 1F , 1F , 1E , 1F , 1E , 1F , 1E ,
1E , 1E , 1E , 1D , 1E , 1E , 1D , 1D ,
1E , 1D , 1D , 1D , 1D , 1C , 1D , 1D ,
1C , 1C , 1C , 1D , 1C , 1C , 1B , 1C ,
1C , 1B , 1C , 1B , 1B , 1B , 1B , 1B ,
1B , 1B , 1A , 1B , 1A , 1B , 1A , 1A ,

1A , 1A , 1A , 19 , 1A , 1A , 19 , 19 ,
1A , 19 , 19 , 19 , 19 , 19 , 18 , 19 ,
18 , 19 , 18 , 18 , 18 , 18 , 18 , 18 ,
18 , 18 , 17 , 18 , 17 , 17 , 18 , 17 ,
17 , 17 , 16 , 17 , 17 , 17 , 16 , 16 ,
17 , 16 , 16 , 16 , 16 , 16 , 16 , 16 ,
15 , 16 , 15 , 16 , 15 , 15 , 15 , 15 ,
15 , 15 , 15 , 15 , 15 , 14 , 15 , 14 ,

BASE>

PRIVATE

: SINQ@ SINQ-TABLE SWAP CELLS + @ ; PRIVATE
: POW2@ POW2-TABLE SWAP CELLS + @ ; PRIVATE
: LOG2I@ LOG2I-TABLE SWAP CELLS + @ ; PRIVATE
: LOG2F@ LOG2F-TABLE SWAP CELLS + @ ; PRIVATE
: LOG2D@ LOG2D-TABLE SWAP CELLS + @ ; PRIVATE
: EXP2F@ EXP2F-TABLE SWAP CELLS + @ ; PRIVATE
: EXP2D@ EXP2D-TABLE SWAP CELLS + @ ; PRIVATE
: ATANF@ ATANF-TABLE SWAP CELLS + @ ; PRIVATE
: ATAND@ ATAND-TABLE SWAP CELLS + @ ; PRIVATE

\ END GENERATED MATH TABLES





: Q15> DUP + >R 0< NEGATE R> + ;

: Q15>R SWAP 16384 UM+ ROT + Q15> ;

: U/MOD >R 0 R> UM/MOD ;

: U/ U/MOD SWAP DROP ;

: U*/ >R UM* R> UM/MOD SWAP DROP ;

: */ROUND
  DUP ABS >R
  */MOD
  SWAP ABS DUP + R@ U< NOT
  IF
    1 +
  THEN
  R> DROP
;

: I*F M* Q15> ;

: BIN>DEG 45 8192 */ROUND ;

: DEG>BIN 360 MOD 8192 45 */ROUND ;

: BIN>DEG.S 45 * 8192 */ROUND ;

: DEG.S>BIN
  DUP 360 * >R
  SWAP R@ MOD SWAP
  45 * 8192 SWAP */ROUND
  R> DROP
;

: STEP16
  0 >R
  DUP 8 AND IF OVER 2 / R> + >R THEN
  DUP 4 AND IF OVER 4 / R> + >R THEN
  DUP 2 AND IF OVER 8 / R> + >R THEN
  DUP 1 AND IF OVER 16 / R> + >R THEN
  DROP DROP R>
;

: RATIOQ12 SWAP 4096 ROT U*/ ;

: LOG2-NORM
  12 SWAP
  BEGIN
    DUP 8192 U< 0 =
  WHILE
    2 U/ SWAP 1 + SWAP
  REPEAT
  BEGIN
    DUP 4096 U< 
  WHILE
    DUP + SWAP 1 - SWAP
  REPEAT
;

: LOG2-FRAC
  4096 - 16 /MOD
  DUP LOG2D@ >R
  LOG2F@
  R> ROT STEP16 +
;

: LOG2
  DUP 0 = IF
    DROP 0
  ELSE
    LOG2-NORM
    SWAP LOG2I@ SWAP LOG2-FRAC +
  THEN
;

: EXP2-FRAC
  DUP 4095 SWAP < IF
    DROP 8192
  ELSE
    16 /MOD
    DUP EXP2D@ >R
    EXP2F@
    R> ROT STEP16 +
  THEN
;

: EXP2
  4096 U/MOD
  >R
  EXP2-FRAC
  R> POW2@ 4096 U*/
;

: B000 0 ;

: B001 182 ;

: B002 364 ;

: B003 546 ;

: B005 910 ;

: B010 1820 ;

: B015 2731 ;

: B030 5461 ;

: B045 8192 ;

: BINIAN/4 16384 ;

: B060 10923 ;

: B075 13653 ;

: B090 BINIAN/4 ;

: B105 19115 ;

: B120 21845 ;

: B135 24576 ;

: B150 27307 ;

: B165 30037 ;

: BINIAN/2 -32768 ;

: B180 BINIAN/2 ;

: B195 -30037 ;

: B210 -27307 ;

: B225 -24576 ;

: B240 -21845 ;

: B255 -19115 ;

: BINIAN3/4 -16384 ;

: B270 BINIAN3/4 ;

: B285 -13653 ;

: B300 -10923 ;

: B315 -8192 ;

: B330 -5461 ;

: B345 -2731 ;

: SINQ 64 / SINQ@ ;

: SIN
  DUP 0 = IF
    DROP 0
  ELSE
    DUP BINIAN/4 = IF
      DROP 32767
    ELSE
      DUP BINIAN/2 = IF
        DROP 0
      ELSE
        DUP BINIAN3/4 = IF
          DROP -32768
        ELSE
          DUP 0< IF
            DUP BINIAN3/4 < IF
              BINIAN/2 + SINQ NEGATE
            ELSE
              NEGATE SINQ NEGATE
            THEN
          ELSE
            DUP BINIAN/4 < IF
              SINQ
            ELSE
              NEGATE BINIAN/2 + SINQ
            THEN
          THEN
        THEN
      THEN
    THEN
  THEN
;

: COS BINIAN/4 + SIN ;

: XCOMP COS I*F ;

: YCOMP SIN I*F ;

: ATANR
  DUP 4096 = IF
    DROP B045
  ELSE
    16 /MOD
    DUP ATAND@ >R
    ATANF@
    R> ROT STEP16 +
  THEN
;

: ATAN2
  2DUP OR 0 = IF
    2DROP 0
  ELSE
    2DUP ABS SWAP ABS
    2DUP U< IF
      RATIOQ12 ATANR B090 SWAP -
    ELSE
      SWAP RATIOQ12 ATANR
    THEN
    >R
    DUP 0< IF
      SWAP 0< IF
        DROP B180 R> +
      ELSE
        DROP B180 R> -
      THEN
    ELSE
      SWAP 0< IF
        DROP R> NEGATE
      ELSE
        DROP R>
      THEN
    THEN
  THEN
;

: SQRT
  0 SWAP 1
  BEGIN
    OVER OVER U< 0 =
  WHILE
    OVER OVER - >R
    SWAP DROP
    2 +
    SWAP 1 + SWAP
    R> SWAP
  REPEAT
  DROP DROP
;
