: EDIT-LINE-CAP 160 ;
: EDIT-REC-SIZE 164 ;
: EDIT-ARENA-SIZE 8192 ;
: EDIT-TEXT-W 80 ;
: EDIT-TEXT-H 23 ;
: EDIT-STATUS-ROW 24 ;
: EDIT-HELP-ROW 25 ;

: EDIT-MSG-NONE 0 ;
: EDIT-MSG-SAVED 1 ;
: EDIT-MSG-BUFFER 2 ;
: EDIT-MSG-LONG 3 ;
: EDIT-MSG-OPEN 4 ;
: EDIT-MSG-READ 5 ;
: EDIT-MSG-WRITE 6 ;
: EDIT-MSG-NEW 7 ;
: EDIT-MSG-NAME 8 ;
: EDIT-MSG-UNSUP 9 ;

: EDIT-USER-OFFSET 256 ;
: EDIT-PATH-SIZE 260 ;

EDIT-USER-OFFSET 0 + USER EDIT-MARK
EDIT-USER-OFFSET 1 + USER EDIT-BASE
EDIT-USER-OFFSET 2 + USER EDIT-HERE
EDIT-USER-OFFSET 3 + USER EDIT-LIMIT
EDIT-USER-OFFSET 4 + USER EDIT-FREE
EDIT-USER-OFFSET 5 + USER EDIT-HEAD
EDIT-USER-OFFSET 6 + USER EDIT-TAIL
EDIT-USER-OFFSET 7 + USER EDIT-CUR
EDIT-USER-OFFSET 8 + USER EDIT-TOP
EDIT-USER-OFFSET 9 + USER EDIT-LINES
EDIT-USER-OFFSET 10 + USER EDIT-CUR#
EDIT-USER-OFFSET 11 + USER EDIT-TOP#
EDIT-USER-OFFSET 12 + USER EDIT-COL
EDIT-USER-OFFSET 13 + USER EDIT-PREF
EDIT-USER-OFFSET 14 + USER EDIT-MODIFIED
EDIT-USER-OFFSET 15 + USER EDIT-INSERT
EDIT-USER-OFFSET 16 + USER EDIT-RUNNING
EDIT-USER-OFFSET 17 + USER EDIT-MSG
EDIT-USER-OFFSET 18 + USER EDIT-PATH-LEN
EDIT-USER-OFFSET 19 + USER EDIT-PATH-BUF#
EDIT-USER-OFFSET 20 + USER EDIT-CLIP-LEN
EDIT-USER-OFFSET 21 + USER EDIT-CLIP-BUF#
EDIT-USER-OFFSET 22 + USER ET1
EDIT-USER-OFFSET 23 + USER ET2
EDIT-USER-OFFSET 24 + USER ET3
EDIT-USER-OFFSET 25 + USER ET4

: EDIT-LINE-NEXT ;
: EDIT-LINE-PREV 1+ ;
: EDIT-LINE-LEN 2 + ;
: EDIT-LINE-FLAGS 3 + ;
: EDIT-LINE-TEXT 4 + ;

: EDIT-LINE-LEN@ EDIT-LINE-LEN @ ;
: EDIT-LINE-LEN! EDIT-LINE-LEN ! ;

: EDIT-LINE-ADDR ( col line -- addr ) SWAP EDIT-LINE-TEXT + ;

: EDIT-PATH-BUF EDIT-PATH-BUF# @ ;

: EDIT-CLIP-BUF EDIT-CLIP-BUF# @ ;

: EDIT-PATH$ EDIT-PATH-BUF EDIT-PATH-LEN @ ;

: EDIT-PATH! DUP EDIT-PATH-LEN ! EDIT-PATH-BUF SWAP CMOVE ;

: EDIT-MSG! EDIT-MSG ! ;

: EDIT-CUR-LEN EDIT-CUR @ EDIT-LINE-LEN@ ;

: EDIT-CUR-ADDR EDIT-CUR @ EDIT-LINE-TEXT ;

: EDIT-LINE-COUNT EDIT-LINES @ ;

: EDIT-COL! DUP EDIT-COL ! EDIT-PREF ! ;

: EDIT-CLEAR-LINE 0 OVER EDIT-LINE-LEN ! DROP ;

: ED-ALLOC EDIT-FREE @ ?DUP IF DUP @ EDIT-FREE ! ELSE EDIT-HERE @ DUP EDIT-REC-SIZE + EDIT-LIMIT
@ SWAP U< IF DROP 0 EXIT THEN DUP EDIT-REC-SIZE + EDIT-HERE ! THEN DUP 0 OVER ! SWAP DROP DUP
  EDIT-LINE-PREV 0 SWAP ! DUP EDIT-LINE-LEN 0 SWAP ! DUP EDIT-LINE-FLAGS 0 SWAP ! ;

: EDIT-FREE-LINE EDIT-FREE @ OVER ! EDIT-FREE ! ;

: EDIT-LINK-AFTER ET1 ! ET2 ! ET1 @ @ ET2 @ ! ET1 @ ET2 @ EDIT-LINE-PREV ! ET2 @ @ ?DUP IF ET2 @
SWAP EDIT-LINE-PREV ! ELSE ET1 @ EDIT-TAIL ! THEN ET1 @ ET2 @ ! ;

: EDIT-UNLINK DUP @ ET1 ! DUP EDIT-LINE-PREV @ ET2 ! ET2 @ IF ET1 @ ET2 @ ! ELSE ET1 @ EDIT-HEAD
! THEN ET1 @ IF ET2 @ ET1 @ EDIT-LINE-PREV ! ELSE ET2 @ EDIT-TAIL ! THEN ;

: EDIT-RESET-BUFFER 0 EDIT-FREE ! EDIT-BASE @ EDIT-HERE ! 0 EDIT-MODIFIED ! 0 EDIT-MSG ! 0
EDIT-COL ! 0 EDIT-PREF ! 0 EDIT-CLIP-LEN ! ED-ALLOC DUP 0= IF DROP EDIT-MSG-BUFFER EDIT-MSG !
  EXIT THEN DUP EDIT-HEAD ! DUP EDIT-TAIL ! DUP EDIT-CUR ! DUP EDIT-TOP ! DROP 1 EDIT-LINES ! 1
  EDIT-CUR# ! 1 EDIT-TOP# ! ;

: EDIT-INIT CP @ EDIT-MARK ! CP @ DUP EDIT-PATH-BUF# ! EDIT-PATH-SIZE + DUP EDIT-CLIP-BUF# !
  EDIT-LINE-CAP + DUP EDIT-BASE ! DUP EDIT-HERE ! EDIT-ARENA-SIZE + EDIT-LIMIT ! EDIT-LIMIT @ CP !
  1 EDIT-INSERT ! EDIT-MSG-NONE EDIT-MSG ! 0 EDIT-PATH-LEN ! EDIT-RESET-BUFFER ;

: EDIT-DONE EDIT-MARK @ CP ! NORMAL CURSOR-ON ;

: EDIT-TRIM-LEN DUP EDIT-LINE-LEN@ ET1 ! BEGIN ET1 @ WHILE DUP EDIT-LINE-TEXT ET1 @ 1- + C@ BL =
IF ET1 @ 1- ET1 ! ELSE DROP ET1 @ EXIT THEN REPEAT DROP 0 ;

: EDIT-EXTEND-CUR DUP EDIT-LINE-CAP > IF DROP EDIT-MSG-LONG EDIT-MSG ! 0 EXIT THEN DUP
EDIT-CUR-LEN <= IF DROP -1 EXIT THEN DUP ET1 ! EDIT-CUR-LEN ET2 ! EDIT-CUR @ EDIT-LINE-TEXT ET2
  @ + ET1 @ ET2 @ - BL FILL ET1 @ EDIT-CUR @ EDIT-LINE-LEN ! DROP -1 ;

: EDIT-ENSURE-VISIBLE BEGIN EDIT-CUR# @ EDIT-TOP# @ < WHILE EDIT-TOP @ EDIT-LINE-PREV @ EDIT-TOP
! EDIT-TOP# @ 1- EDIT-TOP# ! REPEAT BEGIN EDIT-CUR# @ EDIT-TOP# @ EDIT-TEXT-H + >= WHILE
  EDIT-TOP @ @ EDIT-TOP ! EDIT-TOP# @ 1+ EDIT-TOP# ! REPEAT ;

: EDIT-MOVE-UP EDIT-CUR @ EDIT-LINE-PREV @ ?DUP IF EDIT-CUR ! EDIT-CUR# @ 1- EDIT-CUR# !
EDIT-PREF @ EDIT-COL ! EDIT-ENSURE-VISIBLE THEN ;

: EDIT-MOVE-DOWN EDIT-CUR @ @ ?DUP IF EDIT-CUR ! EDIT-CUR# @ 1+ EDIT-CUR# ! EDIT-PREF @ EDIT-COL
! EDIT-ENSURE-VISIBLE THEN ;

: EDIT-MOVE-LEFT EDIT-COL @ IF EDIT-COL @ 1- EDIT-COL ! EDIT-COL @ EDIT-PREF ! THEN ;

: EDIT-MOVE-RIGHT EDIT-COL @ 1+ DUP EDIT-COL ! EDIT-PREF ! ;

: EDIT-MOVE-HOME 0 EDIT-COL! ;

: EDIT-MOVE-END EDIT-CUR-LEN EDIT-COL! ;

: EDIT-PAGE-UP 0 ET1 ! BEGIN ET1 @ EDIT-TEXT-H < WHILE EDIT-MOVE-UP ET1 @ 1+ ET1 ! REPEAT ;

: EDIT-PAGE-DOWN 0 ET1 ! BEGIN ET1 @ EDIT-TEXT-H < WHILE EDIT-MOVE-DOWN ET1 @ 1+ ET1 ! REPEAT ;

: EDIT-SET-MODIFIED -1 EDIT-MODIFIED ! EDIT-MSG-NONE EDIT-MSG ! ;

: EDIT-OVERWRITE-CHAR EDIT-COL @ 1+ EDIT-EXTEND-CUR 0= IF DROP EXIT THEN EDIT-COL @ EDIT-CUR @
EDIT-LINE-ADDR C! EDIT-COL @ 1+ EDIT-COL! EDIT-SET-MODIFIED ;

: EDIT-INSERT-CHAR EDIT-COL @ ET3 ! EDIT-CUR-LEN ET4 ! ET3 @ ET4 @ >= IF ET3 @ 1+ EDIT-EXTEND-CUR
0= IF DROP EXIT THEN EDIT-COL @ EDIT-CUR @ EDIT-LINE-ADDR C! ELSE ET4 @ 1+ EDIT-EXTEND-CUR 0= IF
  DROP EXIT THEN ET3 @ EDIT-CUR @ EDIT-LINE-ADDR DUP 1+ SWAP ET4 @ ET3 @ - CMOVE> EDIT-COL @
  EDIT-CUR @ EDIT-LINE-ADDR C! THEN EDIT-COL @ 1+ EDIT-COL! EDIT-SET-MODIFIED ;

: EDIT-JOIN-NEXT EDIT-CUR @ @ ?DUP 0= IF DROP EXIT THEN DUP ET1 ! EDIT-CUR-LEN ET2 ! ET1 @
EDIT-LINE-LEN@ ET3 ! ET2 @ ET3 @ + EDIT-LINE-CAP > IF EDIT-MSG-LONG EDIT-MSG ! EXIT THEN ET1 @
  EDIT-LINE-TEXT EDIT-CUR @ EDIT-LINE-TEXT ET2 @ + ET3 @ CMOVE ET2 @ ET3 @ + EDIT-CUR @
  EDIT-LINE-LEN ! ET1 @ EDIT-UNLINK ET1 @ EDIT-FREE-LINE EDIT-LINES @ 1- EDIT-LINES !
  EDIT-SET-MODIFIED ;

: EDIT-DELETE-CHAR EDIT-COL @ ET1 ! EDIT-CUR-LEN ET2 ! ET1 @ ET2 @ < IF EDIT-CUR @ ET1 @ 1+
EDIT-LINE-ADDR EDIT-CUR @ ET1 @ EDIT-LINE-ADDR ET2 @ ET1 @ - 1- CMOVE ET2 @ 1- EDIT-CUR @
  EDIT-LINE-LEN ! EDIT-SET-MODIFIED EXIT THEN ET1 @ ET2 @ = IF EDIT-JOIN-NEXT THEN ;

: EDIT-SPLIT-LINE ED-ALLOC DUP 0= IF DROP EDIT-MSG-BUFFER EDIT-MSG ! EXIT THEN DUP ET1 !
EDIT-CUR @ ET2 ! EDIT-COL @ ET3 ! ET2 @ EDIT-LINE-LEN@ ET4 ! ET3 @ ET4 @ < IF ET4 @ ET3 @ - DUP
  ET1 @ EDIT-LINE-LEN ! ET2 @ EDIT-LINE-TEXT ET3 @ + ET1 @ EDIT-LINE-TEXT ROT CMOVE ET3 @ ET2 @
  EDIT-LINE-LEN ! ELSE 0 ET1 @ EDIT-LINE-LEN ! THEN ET1 @ ET2 @ EDIT-LINK-AFTER EDIT-LINES @ 1+
  EDIT-LINES ! ET1 @ EDIT-CUR ! EDIT-CUR# @ 1+ EDIT-CUR# ! 0 EDIT-COL! EDIT-ENSURE-VISIBLE
  EDIT-SET-MODIFIED ;

: EDIT-BACKSPACE EDIT-COL @ 0= IF EDIT-CUR @ EDIT-LINE-PREV @ ?DUP IF DUP EDIT-LINE-LEN@ ET1 !
EDIT-CUR ! EDIT-CUR# @ 1- EDIT-CUR# ! ET1 @ EDIT-COL! EDIT-JOIN-NEXT EDIT-ENSURE-VISIBLE THEN
  EXIT THEN EDIT-COL @ 1- DUP EDIT-COL ! EDIT-PREF ! EDIT-COL @ EDIT-CUR-LEN >= IF EXIT THEN
  EDIT-DELETE-CHAR ;

: EDIT-DELETE-LINE EDIT-LINES @ 1 = IF EDIT-CUR @ EDIT-CLEAR-LINE 0 EDIT-COL! EDIT-SET-MODIFIED
EXIT THEN EDIT-CUR @ ET1 ! ET1 @ @ ?DUP IF DUP EDIT-CUR ! ELSE ET1 @ EDIT-LINE-PREV @ DUP
  EDIT-CUR ! EDIT-CUR# @ 1- EDIT-CUR# ! THEN ET1 @ EDIT-TOP @ = IF EDIT-CUR @ EDIT-TOP !
  EDIT-CUR# @ EDIT-TOP# ! THEN ET1 @ EDIT-UNLINK ET1 @ EDIT-FREE-LINE EDIT-LINES @ 1- EDIT-LINES
  ! EDIT-CUR-LEN EDIT-COL @ MIN EDIT-COL! EDIT-ENSURE-VISIBLE EDIT-SET-MODIFIED ;

: EDIT-COPY-LINE EDIT-CUR @ EDIT-LINE-LEN@ DUP EDIT-CLIP-LEN ! EDIT-CUR @ EDIT-LINE-TEXT
EDIT-CLIP-BUF ROT CMOVE EDIT-MSG-NONE EDIT-MSG ! ;

: EDIT-PASTE-LINE ED-ALLOC DUP 0= IF DROP EDIT-MSG-BUFFER EDIT-MSG ! EXIT THEN DUP ET1 !
EDIT-CLIP-LEN @ DUP ET1 @ EDIT-LINE-LEN ! EDIT-CLIP-BUF ET1 @ EDIT-LINE-TEXT ROT CMOVE ET1 @
  EDIT-CUR @ EDIT-LINK-AFTER ET1 @ EDIT-CUR ! EDIT-LINES @ 1+ EDIT-LINES ! EDIT-CUR# @ 1+
  EDIT-CUR# ! 0 EDIT-COL! EDIT-ENSURE-VISIBLE EDIT-SET-MODIFIED ;

: EDIT-NEW EDIT-RESET-BUFFER EDIT-MSG-NEW EDIT-MSG ! ;

: EDIT-LOAD EDIT-PATH! EDIT-RESET-BUFFER EDIT-PATH$ R/O OPEN-FILE DUP IF SWAP DROP EDIT-MSG-OPEN
EDIT-MSG ! EXIT THEN DROP >R EDIT-HEAD @ ET2 ! -1 ET3 ! BEGIN TIB EDIT-LINE-CAP R@
  READ-LINE DUP IF DROP DROP DROP R> CLOSE-FILE DROP EDIT-MSG-READ EDIT-MSG ! 1 EXIT THEN
  DROP WHILE ET3 @ 0= IF ED-ALLOC DUP 0= IF DROP R> CLOSE-FILE DROP EDIT-MSG-BUFFER EDIT-MSG
  ! 2 EXIT THEN DUP EDIT-TAIL @ EDIT-LINK-AFTER DUP ET2 ! EDIT-LINES @ 1+ EDIT-LINES ! DROP ELSE 0
  ET3 ! THEN DUP ET2 @ EDIT-LINE-LEN ! TIB ET2 @ EDIT-LINE-TEXT ROT CMOVE REPEAT DROP R>
  CLOSE-FILE DROP EDIT-HEAD @ EDIT-CUR ! EDIT-HEAD @ EDIT-TOP ! 1 EDIT-CUR# ! 1 EDIT-TOP# ! 0
  EDIT-COL! 0 EDIT-MODIFIED ! EDIT-MSG-NONE EDIT-MSG ! 0 ;

: EDIT-SAVE EDIT-PATH-LEN @ 0= IF EDIT-MSG-NAME EDIT-MSG ! 1 EXIT THEN EDIT-PATH$ DELETE-FILE
DROP EDIT-PATH$ R/W CREATE-FILE DUP IF SWAP DROP EDIT-MSG-WRITE EDIT-MSG ! EXIT THEN DROP ET4 !
  EDIT-HEAD @ BEGIN DUP WHILE DUP EDIT-TRIM-LEN DUP ET2 ! OVER EDIT-LINE-TEXT ET2 @ ET4 @
  WRITE-LINE DUP IF DROP ET4 @ CLOSE-FILE DROP EDIT-MSG-WRITE EDIT-MSG ! 1 EXIT THEN DROP @
  REPEAT DROP ET4 @ FLUSH-FILE DROP ET4 @ CLOSE-FILE DROP 0 EDIT-MODIFIED ! EDIT-MSG-SAVED
  EDIT-MSG ! 0 ;

: EDIT-.MSG EDIT-MSG @ DUP EDIT-MSG-SAVED = IF DROP ."  Saved" EXIT THEN DUP EDIT-MSG-BUFFER =
IF DROP ."  Buffer full" EXIT THEN DUP EDIT-MSG-LONG = IF DROP ."  Line too long" EXIT THEN DUP
  EDIT-MSG-OPEN = IF DROP ."  Open failed" EXIT THEN DUP EDIT-MSG-READ = IF DROP
  ."  Read failed" EXIT THEN DUP EDIT-MSG-WRITE = IF DROP ."  Write failed" EXIT THEN DUP
  EDIT-MSG-NEW = IF DROP ."  New buffer" EXIT THEN DUP EDIT-MSG-NAME = IF DROP ."  No filename"
  EXIT THEN DUP EDIT-MSG-UNSUP = IF DROP ."  Not in MVP" EXIT THEN DROP ;

: EDIT-DRAW-ROW ET1 ! ET2 ! 1 ET1 @ AT CL-LINE ET2 @ ?DUP IF ET2 @ EDIT-LINE-LEN@ EDIT-TEXT-W
MIN ET3 ! 0 ET4 ! BEGIN ET4 @ ET3 @ < WHILE ET2 @ EDIT-LINE-TEXT ET4 @ + C@ EMIT ET4 @ 1+ ET4 !
  REPEAT THEN ;

: EDIT-DRAW-TEXT EDIT-TOP @ ET1 ! 1 ET2 ! BEGIN ET2 @ EDIT-TEXT-H <= WHILE ET1 @ ET2 @
EDIT-DRAW-ROW ET1 @ IF ET1 @ @ ET1 ! THEN ET2 @ 1+ ET2 ! REPEAT ;

: EDIT-DRAW-STATUS REVERSE 1 EDIT-STATUS-ROW AT CL-LINE EDIT-PATH$ TYPE EDIT-MODIFIED @ IF
."  *" ELSE ."  -" THEN ."  Ln " EDIT-CUR# @ ANSI# ."  Col " EDIT-COL @ 1+ ANSI# EDIT-INSERT @
  IF ."  INS" ELSE ."  OVR" THEN EDIT-.MSG NORMAL ;

: EDIT-DRAW-HELP 1 EDIT-HELP-ROW AT CL-LINE
NORMAL ." 1"  HSL_CYAN BG! BLACK FG! ."       "
NORMAL ." 2"  HSL_CYAN BG! BLACK FG! ." Save  "
NORMAL ." 3"  HSL_CYAN BG! BLACK FG! ."       "
NORMAL ." 4"  HSL_CYAN BG! BLACK FG! ." New   "
NORMAL ." 5"  HSL_CYAN BG! BLACK FG! ." Copy  "
NORMAL ." 6"  HSL_CYAN BG! BLACK FG! ."       "
NORMAL ." 7"  HSL_CYAN BG! BLACK FG! ." Paste "
NORMAL ." 8"  HSL_CYAN BG! BLACK FG! ." DelLn "
NORMAL ." 9"  HSL_CYAN BG! BLACK FG! ."       "
NORMAL ." 10" HSL_CYAN BG! BLACK FG! ." Exit  "
NORMAL
;

: EDIT-PLACE-CURSOR EDIT-CUR# @ EDIT-TOP# @ - 1+ 1 MAX EDIT-TEXT-H MIN ET1 ! EDIT-COL @ 1+ 1 MAX
EDIT-TEXT-W MIN ET2 ! ET2 @ ET1 @ AT ;

: EDIT-REDRAW CURSOR-OFF CLS HOME EDIT-DRAW-TEXT EDIT-DRAW-STATUS EDIT-DRAW-HELP
EDIT-PLACE-CURSOR CURSOR-ON ;

: EDIT-HANDLE-PRINTABLE DUP 32 127 WITHIN IF EDIT-INSERT @ IF EDIT-INSERT-CHAR ELSE
EDIT-OVERWRITE-CHAR THEN EXIT THEN DROP ;

: EDIT-HANDLE-CHAR DUP 8 = IF DROP EDIT-BACKSPACE EXIT THEN DUP 127 = IF DROP EDIT-BACKSPACE EXIT
THEN DUP 13 = IF DROP EDIT-SPLIT-LINE EXIT THEN DUP 10 = IF DROP EDIT-SPLIT-LINE
EXIT THEN DUP 9 = IF DROP BL EDIT-HANDLE-PRINTABLE BL EDIT-HANDLE-PRINTABLE EXIT THEN
EDIT-HANDLE-PRINTABLE ;

: EDIT-HANDLE-EKEY DUP KEY_LEFT = IF DROP EDIT-MOVE-LEFT EXIT THEN DUP KEY_RIGHT = IF DROP
EDIT-MOVE-RIGHT EXIT THEN DUP KEY_UP = IF DROP EDIT-MOVE-UP EXIT THEN DUP KEY_DOWN = IF DROP
  EDIT-MOVE-DOWN EXIT THEN DUP KEY_HOME = IF DROP EDIT-MOVE-HOME EXIT THEN DUP KEY_END = IF DROP
  EDIT-MOVE-END EXIT THEN DUP KEY_PGUP = IF DROP EDIT-PAGE-UP EXIT THEN DUP KEY_PGDN = IF DROP
  EDIT-PAGE-DOWN EXIT THEN DUP KEY_BACKSPACE = IF DROP EDIT-BACKSPACE EXIT THEN DUP KEY_DEL = IF
  DROP EDIT-DELETE-CHAR EXIT THEN DUP KEY_ENTER = IF DROP EDIT-SPLIT-LINE EXIT THEN DUP KEY_INS
  = IF DROP EDIT-INSERT @ 0= EDIT-INSERT ! EXIT THEN DUP KEY_F2 = IF DROP EDIT-SAVE DROP EXIT
  THEN DUP KEY_F4 = IF DROP EDIT-NEW EXIT THEN DUP KEY_F5 = IF DROP EDIT-COPY-LINE EXIT THEN DUP
  KEY_F7 = IF DROP EDIT-PASTE-LINE EXIT THEN DUP KEY_F8 = IF DROP EDIT-DELETE-LINE EXIT THEN DUP
  KEY_F10 = IF DROP 0 EDIT-RUNNING ! EXIT THEN DROP EDIT-MSG-UNSUP EDIT-MSG ! ;

: EDIT-WAIT-INPUT BEGIN ?EKEY IF EDIT-HANDLE-EKEY EXIT THEN ?KEY IF EDIT-HANDLE-CHAR EXIT THEN
AGAIN ;

: EDIT-RUN -1 EDIT-RUNNING ! BEGIN EDIT-RUNNING @ WHILE EDIT-REDRAW EDIT-WAIT-INPUT REPEAT
NORMAL CURSOR-ON CLS HOME ;

: EDIT EDIT-INIT 2DUP EDIT-LOAD DUP IF EDIT-DONE EXIT THEN DROP EDIT-RUN EDIT-DONE 0 ;

: NEW-EDIT EDIT-INIT EDIT-PATH! EDIT-NEW EDIT-RUN EDIT-DONE ;
