\ 10-forth-commander-ui.fs
\ Forth Commander ANSI text-mode renderer.
\
\ This source consumes the enumeration layer from 09-forth-commander.fs and
\ turns it into a stable commander-style two-pane text UI.

FORTH-COMMANDER DEFINITIONS

: FCM-SCREEN-W 80 ;
: FCM-SCREEN-H 25 ;
: FCM-TITLE-ROW 1 ;
: FCM-TOP-BORDER-ROW 2 ;
: FCM-HEADER-ROW1 3 ;
: FCM-HEADER-ROW2 4 ;
: FCM-FIRST-CONTENT-ROW 5 ;
: FCM-LAST-CONTENT-ROW 22 ;
: FCM-BOTTOM-BORDER-ROW 23 ;
: FCM-STATUS-ROW 24 ;
: FCM-HELP-ROW 25 ;
: FCM-LEFT-W 38 ;
: FCM-RIGHT-W 39 ;
: FCM-LIST-ROWS 18 ;
: FCM-LEFT-NAME-W 24 ;

VARIABLE FCM-CTX
VARIABLE FCM-TOP
VARIABLE FCM-RUNNING
VARIABLE FCM-DIRTY
VARIABLE FCM-MSG-LEN
VARIABLE FCM-NAME-LEN
VARIABLE FCM-SAVED-IN
VARIABLE FCM-SAVED-TIB-LEN
VARIABLE FCM-SAVED-TIB-PTR
VARIABLE FCM-SAVED-CONTEXT
VARIABLE FCM-SAVED-CURRENT

CREATE FCM-MSG-BUF 128 ALLOT
CREATE FCM-ACTION-BUF 128 ALLOT

: FC-SPACES 0 MAX 0 ?DO BL EMIT LOOP ;

: FC-TYPE-FIT ( c-addr u width -- )
  >R
  R@
  2DUP
  MIN
  DUP
  NIP
  TYPE
  R>
  SWAP -
  FC-SPACES
;

: FC-CHARS ( ch u -- )
  0 MAX 0 ?DO OVER EMIT LOOP DROP
;

: FCM-CLEAR-MSG 0 FCM-MSG-LEN ! ;

: FCM-SET-MSG ( c-addr u -- )
  DUP FCM-MSG-LEN !
  FCM-MSG-BUF SWAP CMOVE
;

: FCM-SAVE-INPUT
  >IN @ FCM-SAVED-IN !
  #TIB @ FCM-SAVED-TIB-LEN !
  TIB FCM-SAVED-TIB-PTR !
;

: FCM-RESTORE-INPUT
  FCM-SAVED-IN @ >IN !
  FCM-SAVED-TIB-LEN @ #TIB !
  FCM-SAVED-TIB-PTR @ #TIB CELL+ !
;

: FCM-STAGE-NAME ( c-addr u -- )
  DUP 127 MIN FCM-NAME-LEN !
  FCM-ACTION-BUF SWAP CMOVE
  FCM-ACTION-BUF FCM-NAME-LEN @ + BL SWAP C!
  FCM-ACTION-BUF #TIB CELL+ !
  FCM-NAME-LEN @ #TIB !
  0 >IN !
;

: FCM-EXEC-WITH-NAME ( c-addr u xt -- err )
  >R
  FCM-SAVE-INPUT
  FCM-STAGE-NAME
  R> CATCH
  FCM-RESTORE-INPUT
;

: FCM-SELECTED-VOCAB@ FCM-CTX @ FCM-CTX-VOCAB@ ;

: FCM-SELECTED-NAME$ ( -- c-addr u )
  FCM-CTX @ FCM-CTX-LEVEL@ 2 = 0= IF 0 0 EXIT THEN
  FCM-CTX @ FCM-TMP1 !
  FCM-TMP1 @ FCM-CTX-VOCAB@
  FCM-TMP1 @ FCM-CTX-BUCKET@
  FCM-TMP1 @ FCM-CTX-SELECT@ 1-
  FC-WORD-NAME$
;

: FCM-SEE-IN-VOCAB ( c-addr u vocab -- err )
  >R
  CONTEXT @ FCM-SAVED-CONTEXT !
  R@ CONTEXT !
  ['] SEE FCM-EXEC-WITH-NAME
  FCM-SAVED-CONTEXT @ CONTEXT !
  R> DROP
;

: FCM-FORGET-IN-VOCAB ( c-addr u vocab -- err )
  >R
  CURRENT @ FCM-SAVED-CURRENT !
  R@ CURRENT !
  ['] FORGET FCM-EXEC-WITH-NAME
  FCM-SAVED-CURRENT @ CURRENT !
  R> DROP
;

: FCM-MARK-DIRTY -1 FCM-DIRTY ! ;
: FCM-MARK-CLEAN 0 FCM-DIRTY ! ;

: FCM-SEE-SELECTED
  FCM-CTX @ FCM-CTX-LEVEL@ 2 = 0= IF
    S" SEE only on colon definitions" FCM-SET-MSG
    FCM-MARK-DIRTY
    EXIT
  THEN
  FCM-CTX @ FC-SELECT@ FC-ROW-KIND FC-KIND-COLON <> IF
    S" SEE only on colon definitions" FCM-SET-MSG
    FCM-MARK-DIRTY
    EXIT
  THEN
  FCM-SELECTED-NAME$ FCM-SELECTED-VOCAB@ FCM-SEE-IN-VOCAB DUP 0= IF
    DROP FCM-CLEAR-MSG
    FCM-MARK-CLEAN
    EXIT
  THEN
  DROP
  S" SEE failed" FCM-SET-MSG
  FCM-MARK-DIRTY
;

: FCM-FORGET-SELECTED
  FCM-CTX @ FCM-CTX-LEVEL@ 2 = 0= IF
    S" FORGET only on RAM words" FCM-SET-MSG
    FCM-MARK-DIRTY
    EXIT
  THEN
  FCM-CTX @ FC-SELECT@ FC-ROW-KIND FC-KIND-UP = IF
    S" FORGET only on RAM words" FCM-SET-MSG
    FCM-MARK-DIRTY
    EXIT
  THEN
  FCM-CTX @ FC-SELECT@ FC-ROW-ROM? IF
    S" FORGET only on RAM words" FCM-SET-MSG
    FCM-MARK-DIRTY
    EXIT
  THEN
  FCM-SELECTED-NAME$ FCM-SELECTED-VOCAB@ FCM-FORGET-IN-VOCAB DUP 0= IF
    DROP
    FCM-CTX @ FC-SELECT@ FCM-SET-SELECT
    FCM-CLEAR-MSG
    EXIT
  THEN
  DROP
  S" FORGET failed" FCM-SET-MSG
  FCM-MARK-DIRTY
;

: FC-LEVEL-TITLE$ ( ctx -- c-addr u )
  FCM-CTX-LEVEL@ 0= IF S" VOCABULARIES" EXIT THEN
  FCM-CTX-LEVEL@ 1 = IF S" BUCKETS" EXIT THEN
  S" WORDS"
;

: FC-ROW-SEL-CHAR ( ctx index -- ch )
  OVER FC-SELECT@ = IF 62 ELSE 32 THEN
;

: FC-ROW-OPEN-CHAR ( ctx index -- ch )
  OVER FCM-CTX-LEVEL@ 0= IF
    FC-ROW-OPEN? IF 43 ELSE 45 THEN EXIT
  THEN
  DUP 0= IF
    DROP 94 EXIT
  THEN
  FC-ROW-OPEN? IF 43 ELSE 45 THEN
;

: FC-ROW-RES$ ( ctx index -- c-addr u )
  FC-ROW-ROM? IF S" ROM" EXIT THEN
  S" RAM"
;

: FC-ROW-LABEL$ ( ctx index -- c-addr u )
  OVER FCM-CTX-LEVEL@ 0= IF DROP S" VOCAB" EXIT THEN
  DUP 0= IF DROP S" UP" EXIT THEN
  OVER FCM-CTX-LEVEL@ 1 = IF DROP S" BUCK" EXIT THEN
  1- FC-WORD-PRIM? IF S" PRIM" ELSE S" :" THEN
;

: FC-ROW-HIDDEN? ( ctx index -- flag )
  OVER FCM-CTX-LEVEL@ 2 = IF
    1- FC-WORD-HIDDEN?
    EXIT
  THEN
  DROP 0
;

: FC-ROW-VALID? ( ctx index -- flag )
  OVER FC-ROWS U< NIP
;

: FC-EMIT-LEFT-ROW ( ctx index -- )
  2DUP FC-ROW-VALID? 0= IF
    FCM-LEFT-W FC-SPACES
    2DROP EXIT
  THEN
  2DUP FC-ROW-HIDDEN? >R
  2DUP FC-ROW-ROM? IF HSL_AZURE ELSE HSL_GREEN THEN
  R> IF DIM DARKER THEN
  FG!
  2DUP SWAP FC-SELECT@ = IF REVERSE BOLD THEN
  2DUP FC-ROW-SEL-CHAR EMIT BL EMIT
  2DUP FC-ROW-OPEN-CHAR EMIT BL EMIT
  2DUP FC-ROW-RES$ 3 FC-TYPE-FIT BL EMIT
  2DUP FC-ROW-LABEL$ 5 FC-TYPE-FIT BL EMIT
  FC-ROW-NAME$ FCM-LEFT-NAME-W FC-TYPE-FIT
  NORMAL
  2DROP
;

: FCM-RIGHT-LINE$ ( row -- c-addr u )
  DUP 5 = IF DROP S" Companion area" EXIT THEN
  DUP 6 = IF DROP S" Independent from selection" EXIT THEN
  DUP 7 = IF DROP S" SEE output reserved" EXIT THEN
  DUP 8 = IF DROP S" File browsing reserved" EXIT THEN
  DUP 9 = IF DROP S" Diagnostics reserved" EXIT THEN
  DROP 0 0
;

: FCM-DRAW-TITLE
  1 FCM-TITLE-ROW AT CL-LINE
  HSL_CYAN BG! BLACK FG! BOLD
  S" Forth Commander" FCM-SCREEN-W FC-TYPE-FIT
  NORMAL
;

: FCM-DRAW-TOP-BORDER
  1 FCM-TOP-BORDER-ROW AT CL-LINE
  HSL_CYAN FG!
  CP437-TL EMIT
  CP437-HLINE FCM-LEFT-W FC-CHARS
  CP437-TDOWN EMIT
  CP437-HLINE FCM-RIGHT-W FC-CHARS
  CP437-TR EMIT
  NORMAL
;

: FCM-DRAW-BOTTOM-BORDER
  1 FCM-BOTTOM-BORDER-ROW AT CL-LINE
  HSL_CYAN FG!
  CP437-BL EMIT
  CP437-HLINE FCM-LEFT-W FC-CHARS
  CP437-TUP EMIT
  CP437-HLINE FCM-RIGHT-W FC-CHARS
  CP437-BR EMIT
  NORMAL
;

: FCM-DRAW-HEADER-ROW1
  1 FCM-HEADER-ROW1 AT CL-LINE
  CP437-VLINE EMIT
  HSL_AZURE FG! DIM
  FCM-CTX @ FC-PATH$ FCM-LEFT-W FC-TYPE-FIT
  NORMAL
  CP437-VLINE EMIT
  HSL_CYAN FG! BOLD
  S" COMPANION AREA" FCM-RIGHT-W FC-TYPE-FIT
  NORMAL
  CP437-VLINE EMIT
  NORMAL
;

: FCM-DRAW-HEADER-ROW2
  1 FCM-HEADER-ROW2 AT CL-LINE
  CP437-VLINE EMIT
  HSL_CYAN FG! BOLD
  FCM-CTX @ FC-LEVEL-TITLE$ FCM-LEFT-W FC-TYPE-FIT
  NORMAL
  CP437-VLINE EMIT
  HSL_GREEN FG! DIM
  S" STATIC COMPANION" FCM-RIGHT-W FC-TYPE-FIT
  NORMAL
  CP437-VLINE EMIT
  NORMAL
;

: FCM-DRAW-HEADERS
  FCM-DRAW-HEADER-ROW1
  FCM-DRAW-HEADER-ROW2
;

: FCM-DRAW-RIGHT-LINE ( row -- )
  DUP FCM-RIGHT-LINE$ ?DUP IF
    HSL_CYAN FG! DIM
    FCM-RIGHT-W FC-TYPE-FIT
    NORMAL
    DROP
    EXIT
  THEN
  DROP
  FCM-RIGHT-W FC-SPACES
;

: FCM-DRAW-LIST-ROW ( ctx index row -- )
  >R
  1 R@ AT CL-LINE
  CP437-VLINE EMIT
  FCM-EMIT-LEFT-ROW
  CP437-VLINE EMIT
  R@ FCM-DRAW-RIGHT-LINE
  CP437-VLINE EMIT
  NORMAL
  R> DROP
;

: FCM-ROWS@ FCM-CTX @ FC-ROWS ;

: FCM-MAX-TOP
  FCM-ROWS@ FCM-LIST-ROWS - 0 MAX
;

: FCM-ENSURE-VISIBLE
  FCM-CTX @ FC-SELECT@
  FCM-TOP @ U< IF
    FCM-CTX @ FC-SELECT@ FCM-TOP !
  THEN
  FCM-CTX @ FC-SELECT@
  FCM-TOP @ FCM-LIST-ROWS + U< 0= IF
    FCM-CTX @ FC-SELECT@ FCM-LIST-ROWS 1- -
    FCM-TOP !
  THEN
  FCM-TOP @ FCM-MAX-TOP MIN FCM-TOP !
;

: FCM-SET-CTX ( ctx -- )
  ?DUP IF
    FCM-CTX !
    0 FCM-TOP !
    FCM-ENSURE-VISIBLE
    FCM-MARK-DIRTY
  THEN
;

: FCM-SET-SELECT ( n -- )
  0 MAX
  FCM-ROWS@ DUP 0= IF DROP 0 ELSE 1- MIN THEN
  FCM-CTX @ SWAP FC-SELECT!
  FCM-CTX !
  FCM-ENSURE-VISIBLE
  FCM-MARK-DIRTY
;

: FCM-MOVE-UP
  FCM-CLEAR-MSG
  FCM-CTX @ FC-SELECT@ 1- FCM-SET-SELECT
;

: FCM-MOVE-DOWN
  FCM-CLEAR-MSG
  FCM-CTX @ FC-SELECT@ 1+ FCM-SET-SELECT
;

: FCM-MOVE-FIRST
  FCM-CLEAR-MSG
  0 FCM-SET-SELECT
;

: FCM-MOVE-LAST
  FCM-CLEAR-MSG
  FCM-ROWS@ 1- FCM-SET-SELECT
;

: FCM-PAGE-UP
  FCM-CLEAR-MSG
  FCM-CTX @ FC-SELECT@ FCM-LIST-ROWS - FCM-SET-SELECT
;

: FCM-PAGE-DOWN
  FCM-CLEAR-MSG
  FCM-CTX @ FC-SELECT@ FCM-LIST-ROWS + FCM-SET-SELECT
;

: FCM-UP
  FCM-CLEAR-MSG
  FCM-CTX @ FC-UP FCM-SET-CTX
;

: FCM-OPEN
  FCM-CLEAR-MSG
  FCM-CTX @
  FCM-CTX @ FC-SELECT@
  FC-OPEN
  FCM-SET-CTX
;

: FCM-DRAW-LIST
  FCM-TOP @ FCM-TMP1 !
  0 FCM-TMP2 !
  BEGIN
    FCM-TMP2 @ FCM-LIST-ROWS <
  WHILE
    FCM-CTX @
    FCM-TMP1 @ FCM-TMP2 @ +
    FCM-FIRST-CONTENT-ROW FCM-TMP2 @ +
    FCM-DRAW-LIST-ROW
    FCM-TMP2 @ 1+ FCM-TMP2 !
  REPEAT
;

: FCM-DRAW-STATUS
  1 FCM-STATUS-ROW AT CL-LINE
  REVERSE
  FCM-MSG-LEN @ ?DUP IF
    FCM-MSG-BUF SWAP FCM-SCREEN-W FC-TYPE-FIT
  ELSE
    DROP
    FCM-CTX @ FC-PATH$ FCM-SCREEN-W FC-TYPE-FIT
  THEN
  NORMAL
;

: FCM-DRAW-HELP
  1 FCM-HELP-ROW AT CL-LINE
  HSL_CYAN BG! BLACK FG!
  S" ENTER=open  ESC=up  F3=SEE  F8=FORGET  arrows=move  F10=exit" FCM-SCREEN-W FC-TYPE-FIT
  NORMAL
;

: FCM-REDRAW
  CURSOR-OFF
  CLS HOME
  FCM-DRAW-TITLE
  FCM-DRAW-TOP-BORDER
  FCM-DRAW-HEADERS
  FCM-DRAW-LIST
  FCM-DRAW-BOTTOM-BORDER
  FCM-DRAW-STATUS
  FCM-DRAW-HELP
;

: FCM-HANDLE-CHAR
  DUP 13 = IF DROP FCM-OPEN EXIT THEN
  DUP 10 = IF DROP FCM-OPEN EXIT THEN
  DUP 27 = IF DROP FCM-UP EXIT THEN
  DROP
;

: FCM-HANDLE-EKEY
  DUP KEY_LEFT = IF DROP FCM-UP EXIT THEN
  DUP KEY_RIGHT = IF DROP FCM-OPEN EXIT THEN
  DUP KEY_UP = IF DROP FCM-MOVE-UP EXIT THEN
  DUP KEY_DOWN = IF DROP FCM-MOVE-DOWN EXIT THEN
  DUP KEY_HOME = IF DROP FCM-MOVE-FIRST EXIT THEN
  DUP KEY_END = IF DROP FCM-MOVE-LAST EXIT THEN
  DUP KEY_PGUP = IF DROP FCM-PAGE-UP EXIT THEN
  DUP KEY_PGDN = IF DROP FCM-PAGE-DOWN EXIT THEN
  DUP KEY_F3 = IF DROP FCM-SEE-SELECTED EXIT THEN
  DUP KEY_F8 = IF DROP FCM-FORGET-SELECTED EXIT THEN
  DUP KEY_F10 = IF DROP 0 FCM-RUNNING ! EXIT THEN
  DROP
;

: FCM-WAIT-INPUT
  BEGIN
    ?EKEY IF FCM-HANDLE-EKEY EXIT THEN
    ?KEY IF FCM-HANDLE-CHAR EXIT THEN
  AGAIN
;

: FCM-RUN
  FC-ROOT-CTX FCM-SET-CTX
  FCM-CLEAR-MSG
  FCM-MARK-DIRTY
  -1 FCM-RUNNING !
  BEGIN
    FCM-RUNNING @
  WHILE
    FCM-DIRTY @ IF
      FCM-REDRAW
      FCM-MARK-CLEAN
    THEN
    FCM-WAIT-INPUT
  REPEAT
  NORMAL CURSOR-ON CLS HOME
;
