\ 04-ansi.fs
\ ANSI terminal control core and packed-color helpers.

: ESC 27 EMIT ;

: CSI ESC ." [" ;

\ BEGIN GENERATED ANSI TABLES
\ Generated by V5/Simulator/generate_ansi_tables.py.
\ Packed hues 0..11 use natural nearest ANSI 6x6x6 mapping.
\ Hue 15 maps to a 16-level neutral grayscale ramp using (S << 2) | L.
