"""Primitive opcode metadata for the V4 microcoded execution model."""

_primitives: dict[str, dict[str, int | None | str | bool]] = {
    "NOP": {"opcode": 0, "operands": None, "stack": "( -- )", "interpreted": False, "shadow": False},
    "jump": {"opcode": 1, "operands": None, "stack": "( -- )", "interpreted": False, "shadow": False},
    "?rx": {"opcode": 2, "operands": None, "stack": "( -- c T | F)", "interpreted": True, "shadow": True},
    "tx!": {"opcode": 3, "operands": None, "stack": "( c -- )", "interpreted": True, "shadow": True},
    "doLIT": {"opcode": 4, "operands": 1, "stack": "( -- w )", "interpreted": False, "shadow": False},
    "doLIST": {"opcode": 5, "operands": None, "stack": "( a -- )", "interpreted": False, "shadow": False},
    "doVAR": {"opcode": 6, "operands": None, "stack": "( -- a )", "interpreted": False, "shadow": False},
    "doNEXT": {"opcode": 7, "operands": None, "stack": "( -- ; R: -u -- -u | )", "interpreted": False, "shadow": False},
    "?branch": {"opcode": 8, "operands": 1, "stack": "( f -- )", "interpreted": False, "shadow": False},
    "branch": {"opcode": 9, "operands": 1, "stack": "( -- )", "interpreted": False, "shadow": False},
    "EXECUTE": {"opcode": 10, "operands": None, "stack": "( xt -- )", "interpreted": False, "shadow": False},
    "EXIT": {"opcode": 11, "operands": None, "stack": "", "interpreted": False, "shadow": True},
    "!": {"opcode": 12, "operands": None, "stack": "( w a -- )", "interpreted": True, "shadow": True},
    "@": {"opcode": 13, "operands": None, "stack": "( a -- w )", "interpreted": True, "shadow": True},
    "C!": {"opcode": 14, "operands": None, "stack": "( c b -- )", "interpreted": True, "shadow": True},
    "C@": {"opcode": 15, "operands": None, "stack": "( b -- c )", "interpreted": True, "shadow": True},
    "RP!": {"opcode": 16, "operands": None, "stack": "( a -- )", "interpreted": True, "shadow": True},
    "RP@": {"opcode": 17, "operands": None, "stack": "( -- a )", "interpreted": True, "shadow": True},
    "R>": {"opcode": 18, "operands": None, "stack": "( -- w )", "interpreted": True, "shadow": True},
    "R@": {"opcode": 19, "operands": None, "stack": "( -- w )", "interpreted": True, "shadow": True},
    ">R": {"opcode": 20, "operands": None, "stack": "( w -- )", "interpreted": True, "shadow": True},
    "SP@": {"opcode": 21, "operands": None, "stack": "( -- a )", "interpreted": True, "shadow": True},
    "SP!": {"opcode": 22, "operands": None, "stack": "( a -- )", "interpreted": True, "shadow": True},
    "DROP": {"opcode": 23, "operands": None, "stack": "( w -- )", "interpreted": True, "shadow": True},
    "DUP": {"opcode": 24, "operands": None, "stack": "( w -- w w)", "interpreted": True, "shadow": True},
    "SWAP": {"opcode": 25, "operands": None, "stack": "( w1 w2 -- w2 w1 )", "interpreted": True, "shadow": True},
    "OVER": {"opcode": 26, "operands": None, "stack": "( w1 w2 -- w1 w2 w1 )", "interpreted": True, "shadow": True},
    "0<": {"opcode": 27, "operands": None, "stack": "( n -- f )", "interpreted": True, "shadow": True},
    "AND": {"opcode": 28, "operands": None, "stack": "( w w -- w )", "interpreted": True, "shadow": True},
    "OR": {"opcode": 29, "operands": None, "stack": "( w w -- w )", "interpreted": True, "shadow": True},
    "XOR": {"opcode": 30, "operands": None, "stack": "( w w -- w )", "interpreted": True, "shadow": True},
    "UM+": {"opcode": 31, "operands": None, "stack": "( w w -- w cy )", "interpreted": True, "shadow": True},
    "<<4": {"opcode": 32, "operands": None, "stack": "( w -- w << 4)", "interpreted": False, "shadow": True},
    "<<8": {"opcode": 33, "operands": None, "stack": "( w -- w << 8)", "interpreted": False, "shadow": True},
    "<<9": {"opcode": 34, "operands": None, "stack": "( w -- w << 9)", "interpreted": False, "shadow": True},
    "0=": {"opcode": 35, "operands": None, "stack": "( w -- f )", "interpreted": True, "shadow": True},
    "1+": {"opcode": 36, "operands": None, "stack": "( w -- w + 1)", "interpreted": True, "shadow": True},
    "1-": {"opcode": 37, "operands": None, "stack": "( w -- w - 1)", "interpreted": True, "shadow": True},
    "2+": {"opcode": 38, "operands": None, "stack": "( w -- w + 2)", "interpreted": True, "shadow": True},
    "2-": {"opcode": 39, "operands": None, "stack": "( w -- w - 2)", "interpreted": True, "shadow": True},
    "HOPEN": {"opcode": 40, "operands": None, "stack": "( c-addr u fam -- fileid ior )", "interpreted": True, "shadow": False, "host": True},
    "HCREATE": {"opcode": 41, "operands": None, "stack": "( c-addr u fam -- fileid ior )", "interpreted": True, "shadow": False, "host": True},
    "HCLOSE": {"opcode": 42, "operands": None, "stack": "( fileid -- ior )", "interpreted": True, "shadow": False, "host": True},
    "HREADLN": {"opcode": 43, "operands": None, "stack": "( c-addr u1 fileid -- u2 flag ior )", "interpreted": True, "shadow": False, "host": True},
    "HWRITELN": {"opcode": 44, "operands": None, "stack": "( c-addr u fileid -- ior )", "interpreted": True, "shadow": False, "host": True},
    "HSEEK": {"opcode": 45, "operands": None, "stack": "( ud fileid -- ior )", "interpreted": True, "shadow": False, "host": True},
    "HTELL": {"opcode": 46, "operands": None, "stack": "( fileid -- ud ior )", "interpreted": True, "shadow": False, "host": True},
    "HSIZE": {"opcode": 47, "operands": None, "stack": "( fileid -- ud ior )", "interpreted": True, "shadow": False, "host": True},
    "HFLUSH": {"opcode": 48, "operands": None, "stack": "( fileid -- ior )", "interpreted": True, "shadow": False, "host": True},
    "HDELETE": {"opcode": 49, "operands": None, "stack": "( c-addr u -- ior )", "interpreted": True, "shadow": False, "host": True},
    "HRENAME": {"opcode": 50, "operands": None, "stack": "( c-addr1 u1 c-addr2 u2 -- ior )", "interpreted": True, "shadow": False, "host": True},
    "MUL_SETUP": {"opcode": 51, "operands": None, "stack": "( u1 u2 -- 0 0 )", "interpreted": True, "shadow": True},
    "MUL_STEP_ACC": {"opcode": 52, "operands": None, "stack": "( rhi rlo -- rhi' rlo' )", "interpreted": True, "shadow": True},
    "NOT": {"opcode": 53, "operands": None, "stack": "( w -- ~w )", "interpreted": True, "shadow": True},
    "SUB": {"opcode": 54, "operands": None, "stack": "( w1 w2 -- w1-w2 )", "interpreted": True, "shadow": True},
    "NEGATE": {"opcode": 55, "operands": None, "stack": "( n -- -n )", "interpreted": True, "shadow": True},
    "INC": {"opcode": 56, "operands": None, "stack": "( w -- w+1 )", "interpreted": True, "shadow": True},
    "DEC": {"opcode": 57, "operands": None, "stack": "( w -- w-1 )", "interpreted": True, "shadow": True},
    "ZERO": {"opcode": 58, "operands": None, "stack": "( w -- 0 )", "interpreted": True, "shadow": True},
    "U+": {"opcode": 59, "operands": None, "stack": "( w w -- w )", "interpreted": True, "shadow": True},
    "2*": {"opcode": 60, "operands": None, "stack": "( w -- 2w )", "interpreted": True, "shadow": True},
}
