import asm
from asm import colon, comment, ds, dw, label, skip_user, user, variable


def emit_precompiled_03_fstrings() -> None:
    comment('precompiled from forth/Forth Sources/03-fstrings.fs')
    colon('~err', [], public=False)
    dw(['doLIT', -1])
    ds('abort"', 'bad f-string')
    dw(['EXIT'])
    colon('~pad', [], public=False)
    dw(['doLIT', 0, 'MAX', 'DUP', '?branch', 'PC_03_2Dfstrings__7Epad_IF_FALSE_1', 'doLIT', 1, '-', '~pad', 'BL', '%appc', 'branch', 'PC_03_2Dfstrings__7Epad_IF_END_2'])
    label('PC_03_2Dfstrings__7Epad_IF_FALSE_1')
    dw(['DROP'])
    label('PC_03_2Dfstrings__7Epad_IF_END_2')
    dw(['EXIT'])
    colon('~wtype', [], public=False)
    dw(['%mtw', '@', 'OVER', '-', '~pad', '%appb', 'EXIT'])
    colon('~char', [], public=False)
    dw(['DUP', 'doLIT', 256, 'U<', '?branch', 'PC_03_2Dfstrings__7Echar_IF_FALSE_1', 'EXIT'])
    label('PC_03_2Dfstrings__7Echar_IF_FALSE_1')
    dw(['doLIT', 256, '/MOD', 'SWAP', 'DROP', 'EXIT'])
    colon('~next-char', [], public=False)
    dw(['SWAP', 'doLIT', 1, '+', 'SWAP', 'doLIT', 1, '-', 'EXIT'])
    colon('~nzlen', [], public=False)
    dw(['DUP', '?branch', 'PC_03_2Dfstrings__7Enzlen_IF_FALSE_1', 'OVER', 'C@', '~char', '?branch', 'PC_03_2Dfstrings__7Enzlen_IF_FALSE_2', 'doLIT', 1, 'branch', 'PC_03_2Dfstrings__7Enzlen_IF_END_3'])
    label('PC_03_2Dfstrings__7Enzlen_IF_FALSE_2')
    dw(['doLIT', 0])
    label('PC_03_2Dfstrings__7Enzlen_IF_END_3')
    dw(['>R', '~next-char', '~nzlen', 'R>', '+', 'branch', 'PC_03_2Dfstrings__7Enzlen_IF_END_4'])
    label('PC_03_2Dfstrings__7Enzlen_IF_FALSE_1')
    dw(['2DROP', 'doLIT', 0])
    label('PC_03_2Dfstrings__7Enzlen_IF_END_4')
    dw(['EXIT'])
    colon('~appnz', [], public=False)
    dw(['DUP', '?branch', 'PC_03_2Dfstrings__7Eappnz_IF_FALSE_1', 'OVER', 'C@', '~char', '?DUP', '?branch', 'PC_03_2Dfstrings__7Eappnz_IF_FALSE_2', '%appc', 'branch', 'PC_03_2Dfstrings__7Eappnz_IF_END_3'])
    label('PC_03_2Dfstrings__7Eappnz_IF_FALSE_2')
    dw(['DROP'])
    label('PC_03_2Dfstrings__7Eappnz_IF_END_3')
    dw(['~next-char', '~appnz', 'branch', 'PC_03_2Dfstrings__7Eappnz_IF_END_4'])
    label('PC_03_2Dfstrings__7Eappnz_IF_FALSE_1')
    dw(['2DROP'])
    label('PC_03_2Dfstrings__7Eappnz_IF_END_4')
    dw(['EXIT'])
    colon('~wtype-nz', [], public=False)
    dw(['2DUP', '~nzlen', '%mtw', '@', 'SWAP', '-', '~pad', '~appnz', 'EXIT'])
    colon('~xstr', [], public=False)
    dw(['BASE', '@', '>R', 'HEX', '<#', '#S', '#>', 'R>', 'BASE', '!', 'EXIT'])
    colon('~pdigits', [], public=False)
    dw(['DUP', '?branch', 'PC_03_2Dfstrings__7Epdigits_IF_FALSE_1', 'doLIT', 1, '-', '>R', '#', 'R>', '~pdigits', 'branch', 'PC_03_2Dfstrings__7Epdigits_IF_END_2'])
    label('PC_03_2Dfstrings__7Epdigits_IF_FALSE_1')
    dw(['DROP'])
    label('PC_03_2Dfstrings__7Epdigits_IF_END_2')
    dw(['EXIT'])
    colon('~pstr', [], public=False)
    dw(['DUP', '>R', 'ABS', '<#', '%mtp', '@', 'DUP', '?branch', 'PC_03_2Dfstrings__7Epstr_IF_FALSE_1', '~pdigits', 'doLIT', 46, 'HOLD', 'branch', 'PC_03_2Dfstrings__7Epstr_IF_END_2'])
    label('PC_03_2Dfstrings__7Epstr_IF_FALSE_1')
    dw(['DROP'])
    label('PC_03_2Dfstrings__7Epstr_IF_END_2')
    dw(['#S', 'R>', 'SIGN', '#>', 'EXIT'])
    colon('~outd', [], public=False)
    dw(['%mtp', '@', '0<', '?branch', 'PC_03_2Dfstrings__7Eoutd_IF_FALSE_1', 'str', '~wtype-nz', 'branch', 'PC_03_2Dfstrings__7Eoutd_IF_END_2'])
    label('PC_03_2Dfstrings__7Eoutd_IF_FALSE_1')
    dw(['~pstr', '~wtype-nz'])
    label('PC_03_2Dfstrings__7Eoutd_IF_END_2')
    dw(['EXIT'])
    colon('~outu', [], public=False)
    dw(['%mtp', '@', '0<', '?branch', 'PC_03_2Dfstrings__7Eoutu_IF_FALSE_1', '<#', '#S', '#>', '~wtype-nz', 'branch', 'PC_03_2Dfstrings__7Eoutu_IF_END_2'])
    label('PC_03_2Dfstrings__7Eoutu_IF_FALSE_1')
    dw(['~err'])
    label('PC_03_2Dfstrings__7Eoutu_IF_END_2')
    dw(['EXIT'])
    colon('~outx', [], public=False)
    dw(['%mtp', '@', '0<', '?branch', 'PC_03_2Dfstrings__7Eoutx_IF_FALSE_1', '~xstr', '~wtype-nz', 'branch', 'PC_03_2Dfstrings__7Eoutx_IF_END_2'])
    label('PC_03_2Dfstrings__7Eoutx_IF_FALSE_1')
    dw(['~err'])
    label('PC_03_2Dfstrings__7Eoutx_IF_END_2')
    dw(['EXIT'])
    colon('~outc', [], public=False)
    dw(['%mtp', '@', '0<', '?branch', 'PC_03_2Dfstrings__7Eoutc_IF_FALSE_1', '%mtw', '@', 'doLIT', 1, '-', '~pad', '%appc', 'branch', 'PC_03_2Dfstrings__7Eoutc_IF_END_2'])
    label('PC_03_2Dfstrings__7Eoutc_IF_FALSE_1')
    dw(['~err'])
    label('PC_03_2Dfstrings__7Eoutc_IF_END_2')
    dw(['EXIT'])
    colon('~outs', [], public=False)
    dw(['%mtp', '@', '0<', '?branch', 'PC_03_2Dfstrings__7Eouts_IF_FALSE_1', '~wtype', 'branch', 'PC_03_2Dfstrings__7Eouts_IF_END_2'])
    label('PC_03_2Dfstrings__7Eouts_IF_FALSE_1')
    dw(['~err'])
    label('PC_03_2Dfstrings__7Eouts_IF_END_2')
    dw(['EXIT'])
    colon('~pow10', [], public=False)
    dw(['DUP', '?branch', 'PC_03_2Dfstrings__7Epow10_IF_FALSE_1', 'doLIT', 1, '-', '~pow10', 'doLIT', 10, '*', 'branch', 'PC_03_2Dfstrings__7Epow10_IF_END_2'])
    label('PC_03_2Dfstrings__7Epow10_IF_FALSE_1')
    dw(['DROP', 'doLIT', 1])
    label('PC_03_2Dfstrings__7Epow10_IF_END_2')
    dw(['EXIT'])
    colon('~outa', [], public=False)
    dw(['%mtp', '@', '0<', '?branch', 'PC_03_2Dfstrings__7Eouta_IF_FALSE_1', 'doLIT', 0, '%mtp', '!'])
    label('PC_03_2Dfstrings__7Eouta_IF_FALSE_1')
    dw(['%mtp', '@', '?branch', 'PC_03_2Dfstrings__7Eouta_IF_FALSE_2', '%mtp', '@', '~pow10', 'BIN>DEG.S', 'branch', 'PC_03_2Dfstrings__7Eouta_IF_END_3'])
    label('PC_03_2Dfstrings__7Eouta_IF_FALSE_2')
    dw(['BIN>DEG'])
    label('PC_03_2Dfstrings__7Eouta_IF_END_3')
    dw(['~outd', 'EXIT'])
    colon('~c@', [], public=False)
    dw(['%mta', '@', 'C@', 'EXIT'])
    colon('~width-digits', [], public=False)
    dw(['%mtu', '@', '?branch', 'PC_03_2Dfstrings__7Ewidth_2Ddigits_IF_FALSE_1', '~c@', 'doLIT', 48, 'doLIT', 58, 'WITHIN', '?branch', 'PC_03_2Dfstrings__7Ewidth_2Ddigits_IF_FALSE_2', '~c@', 'doLIT', 48, '-', '%mtw', '@', 'doLIT', 10, '*', '+', '%mtw', '!', 'doLIT', 1, '%adv', '~width-digits'])
    label('PC_03_2Dfstrings__7Ewidth_2Ddigits_IF_FALSE_2')
    label('PC_03_2Dfstrings__7Ewidth_2Ddigits_IF_FALSE_1')
    dw(['EXIT'])
    colon('~prec-digits', [], public=False)
    dw(['%mtu', '@', '?branch', 'PC_03_2Dfstrings__7Eprec_2Ddigits_IF_FALSE_1', '~c@', 'doLIT', 48, 'doLIT', 58, 'WITHIN', '?branch', 'PC_03_2Dfstrings__7Eprec_2Ddigits_IF_FALSE_2', 'doLIT', -1, '%mtf', '!', '~c@', 'doLIT', 48, '-', '%mtp', '@', 'doLIT', 10, '*', '+', '%mtp', '!', 'doLIT', 1, '%adv', '~prec-digits'])
    label('PC_03_2Dfstrings__7Eprec_2Ddigits_IF_FALSE_2')
    label('PC_03_2Dfstrings__7Eprec_2Ddigits_IF_FALSE_1')
    dw(['EXIT'])
    colon('~default?', [], public=False)
    dw(['~c@', 'doLIT', 125, '=', 'EXIT'])
    colon('~type-sa', [], public=False)
    dw(['DUP', 'doLIT', 115, '=', '?branch', 'PC_03_2Dfstrings__7Etype_2Dsa_IF_FALSE_1', 'DROP', '~outs', 'branch', 'PC_03_2Dfstrings__7Etype_2Dsa_IF_END_2'])
    label('PC_03_2Dfstrings__7Etype_2Dsa_IF_FALSE_1')
    dw(['DUP', 'doLIT', 97, '=', '?branch', 'PC_03_2Dfstrings__7Etype_2Dsa_IF_FALSE_3', 'DROP', '~outa', 'branch', 'PC_03_2Dfstrings__7Etype_2Dsa_IF_END_4'])
    label('PC_03_2Dfstrings__7Etype_2Dsa_IF_FALSE_3')
    dw(['DROP', '~err'])
    label('PC_03_2Dfstrings__7Etype_2Dsa_IF_END_4')
    label('PC_03_2Dfstrings__7Etype_2Dsa_IF_END_2')
    dw(['EXIT'])
    colon('~type-dispatch', [], public=False)
    dw(['DUP', 'doLIT', 100, '=', '?branch', 'PC_03_2Dfstrings__7Etype_2Ddispatch_IF_FALSE_1', 'DROP', '~outd', 'branch', 'PC_03_2Dfstrings__7Etype_2Ddispatch_IF_END_2'])
    label('PC_03_2Dfstrings__7Etype_2Ddispatch_IF_FALSE_1')
    dw(['DUP', 'doLIT', 117, '=', '?branch', 'PC_03_2Dfstrings__7Etype_2Ddispatch_IF_FALSE_3', 'DROP', '~outu', 'branch', 'PC_03_2Dfstrings__7Etype_2Ddispatch_IF_END_4'])
    label('PC_03_2Dfstrings__7Etype_2Ddispatch_IF_FALSE_3')
    dw(['DUP', 'doLIT', 120, '=', '?branch', 'PC_03_2Dfstrings__7Etype_2Ddispatch_IF_FALSE_5', 'DROP', '~outx', 'branch', 'PC_03_2Dfstrings__7Etype_2Ddispatch_IF_END_6'])
    label('PC_03_2Dfstrings__7Etype_2Ddispatch_IF_FALSE_5')
    dw(['DUP', 'doLIT', 99, '=', '?branch', 'PC_03_2Dfstrings__7Etype_2Ddispatch_IF_FALSE_7', 'DROP', '~outc', 'branch', 'PC_03_2Dfstrings__7Etype_2Ddispatch_IF_END_8'])
    label('PC_03_2Dfstrings__7Etype_2Ddispatch_IF_FALSE_7')
    dw(['~type-sa'])
    label('PC_03_2Dfstrings__7Etype_2Ddispatch_IF_END_8')
    label('PC_03_2Dfstrings__7Etype_2Ddispatch_IF_END_6')
    label('PC_03_2Dfstrings__7Etype_2Ddispatch_IF_END_4')
    label('PC_03_2Dfstrings__7Etype_2Ddispatch_IF_END_2')
    dw(['EXIT'])
    colon('~field-tail', [], public=False)
    dw(['doLIT', 1, '%adv', '%mtu', '@', '?DUP', '?branch', 'PC_03_2Dfstrings__7Efield_2Dtail_IF_FALSE_1', 'DROP', 'branch', 'PC_03_2Dfstrings__7Efield_2Dtail_IF_END_2'])
    label('PC_03_2Dfstrings__7Efield_2Dtail_IF_FALSE_1')
    ds('abort"', 'bad f-string')
    label('PC_03_2Dfstrings__7Efield_2Dtail_IF_END_2')
    dw(['~c@', 'doLIT', 125, 'XOR'])
    ds('abort"', 'bad f-string')
    dw(['doLIT', 1, '%adv', '~type-dispatch', 'EXIT'])
    colon('~field', [], public=False)
    dw(['doLIT', 1, '%adv', 'doLIT', 0, '%mtw', '!', 'doLIT', -1, '%mtp', '!', '%mtu', '@', '?DUP', '?branch', 'PC_03_2Dfstrings__7Efield_IF_FALSE_1', 'DROP', 'branch', 'PC_03_2Dfstrings__7Efield_IF_END_2'])
    label('PC_03_2Dfstrings__7Efield_IF_FALSE_1')
    ds('abort"', 'bad f-string')
    label('PC_03_2Dfstrings__7Efield_IF_END_2')
    dw(['~default?', '?branch', 'PC_03_2Dfstrings__7Efield_IF_FALSE_3', 'doLIT', 1, '%adv', '~outd', 'branch', 'PC_03_2Dfstrings__7Efield_IF_END_4'])
    label('PC_03_2Dfstrings__7Efield_IF_FALSE_3')
    dw(['~width-digits', '%mtu', '@', '?DUP', '?branch', 'PC_03_2Dfstrings__7Efield_IF_FALSE_5', 'DROP', 'branch', 'PC_03_2Dfstrings__7Efield_IF_END_6'])
    label('PC_03_2Dfstrings__7Efield_IF_FALSE_5')
    ds('abort"', 'bad f-string')
    label('PC_03_2Dfstrings__7Efield_IF_END_6')
    dw(['~c@', 'doLIT', 46, '=', '?branch', 'PC_03_2Dfstrings__7Efield_IF_FALSE_7', 'doLIT', 1, '%adv', 'doLIT', 0, '%mtp', '!', 'doLIT', 0, '%mtf', '!', '~prec-digits', '%mtf', '@', '?DUP', '?branch', 'PC_03_2Dfstrings__7Efield_IF_FALSE_8', 'DROP', 'branch', 'PC_03_2Dfstrings__7Efield_IF_END_9'])
    label('PC_03_2Dfstrings__7Efield_IF_FALSE_8')
    ds('abort"', 'bad f-string')
    label('PC_03_2Dfstrings__7Efield_IF_END_9')
    label('PC_03_2Dfstrings__7Efield_IF_FALSE_7')
    dw(['~c@', 'DUP', 'doLIT', 125, '=', '?branch', 'PC_03_2Dfstrings__7Efield_IF_FALSE_10', 'DROP', 'doLIT', 1, '%adv', '~outd', 'branch', 'PC_03_2Dfstrings__7Efield_IF_END_11'])
    label('PC_03_2Dfstrings__7Efield_IF_FALSE_10')
    dw(['~field-tail'])
    label('PC_03_2Dfstrings__7Efield_IF_END_11')
    label('PC_03_2Dfstrings__7Efield_IF_END_4')
    dw(['EXIT'])
    colon('~eval-lbrace', [], public=False)
    dw(['doLIT', 1, '%mtu', '@', 'U<', '?branch', 'PC_03_2Dfstrings__7Eeval_2Dlbrace_IF_FALSE_1', '%mta', '@', 'doLIT', 1, '+', 'C@', 'doLIT', 123, '=', '?branch', 'PC_03_2Dfstrings__7Eeval_2Dlbrace_IF_FALSE_2', 'doLIT', 123, '%appc', 'doLIT', 2, '%adv', 'branch', 'PC_03_2Dfstrings__7Eeval_2Dlbrace_IF_END_3'])
    label('PC_03_2Dfstrings__7Eeval_2Dlbrace_IF_FALSE_2')
    dw(['~field'])
    label('PC_03_2Dfstrings__7Eeval_2Dlbrace_IF_END_3')
    dw(['branch', 'PC_03_2Dfstrings__7Eeval_2Dlbrace_IF_END_4'])
    label('PC_03_2Dfstrings__7Eeval_2Dlbrace_IF_FALSE_1')
    dw(['~field'])
    label('PC_03_2Dfstrings__7Eeval_2Dlbrace_IF_END_4')
    dw(['EXIT'])
    colon('~eval-rbrace', [], public=False)
    dw(['doLIT', 1, '%mtu', '@', 'U<', '?branch', 'PC_03_2Dfstrings__7Eeval_2Drbrace_IF_FALSE_1', '%mta', '@', 'doLIT', 1, '+', 'C@', 'doLIT', 125, '=', '?branch', 'PC_03_2Dfstrings__7Eeval_2Drbrace_IF_FALSE_2', 'doLIT', 125, '%appc', 'doLIT', 2, '%adv', 'branch', 'PC_03_2Dfstrings__7Eeval_2Drbrace_IF_END_3'])
    label('PC_03_2Dfstrings__7Eeval_2Drbrace_IF_FALSE_2')
    dw(['~err'])
    label('PC_03_2Dfstrings__7Eeval_2Drbrace_IF_END_3')
    dw(['branch', 'PC_03_2Dfstrings__7Eeval_2Drbrace_IF_END_4'])
    label('PC_03_2Dfstrings__7Eeval_2Drbrace_IF_FALSE_1')
    dw(['~err'])
    label('PC_03_2Dfstrings__7Eeval_2Drbrace_IF_END_4')
    dw(['EXIT'])
    colon('~eval', [], public=False)
    dw(['2DUP', 'DROP', '%mta', '!', '%mtu', '!', 'DROP', '%clr'])
    label('PC_03_2Dfstrings__7Eeval_BEGIN_1')
    dw(['%mtu', '@', '?branch', 'PC_03_2Dfstrings__7Eeval_WHILE_END_2', '~c@', 'DUP', 'doLIT', 123, '=', '?branch', 'PC_03_2Dfstrings__7Eeval_IF_FALSE_3', 'DROP', '~eval-lbrace', 'branch', 'PC_03_2Dfstrings__7Eeval_IF_END_4'])
    label('PC_03_2Dfstrings__7Eeval_IF_FALSE_3')
    dw(['DUP', 'doLIT', 125, '=', '?branch', 'PC_03_2Dfstrings__7Eeval_IF_FALSE_5', 'DROP', '~eval-rbrace', 'branch', 'PC_03_2Dfstrings__7Eeval_IF_END_6'])
    label('PC_03_2Dfstrings__7Eeval_IF_FALSE_5')
    dw(['%appc', 'doLIT', 1, '%adv'])
    label('PC_03_2Dfstrings__7Eeval_IF_END_6')
    label('PC_03_2Dfstrings__7Eeval_IF_END_4')
    dw(['branch', 'PC_03_2Dfstrings__7Eeval_BEGIN_1'])
    label('PC_03_2Dfstrings__7Eeval_WHILE_END_2')
    dw(['%ret', 'EXIT'])
    colon('~run', [], compile_only=True)
    dw(['do$', 'COUNT', '~eval', 'EXIT'])
    colon('~"|', [], compile_only=True)
    dw(['~run', 'EXIT'])
    colon('F"', [], immediate=True)
    dw(['STATE', '@', '?branch', 'PC_03_2Dfstrings_F_22_IF_FALSE_1', 'doLIT', 34, 'PARSE', 'UNESCAPE', 'COMPILE', '~run', 'ESC,"', 'branch', 'PC_03_2Dfstrings_F_22_IF_END_2'])
    label('PC_03_2Dfstrings_F_22_IF_FALSE_1')
    dw(['doLIT', 34, 'PARSE', 'UNESCAPE', '~eval'])
    label('PC_03_2Dfstrings_F_22_IF_END_2')
    dw(['EXIT'])
