import asm
from asm import colon, comment, ds, dw, label, skip_user, user, variable


def emit_precompiled_08_editor() -> None:
    comment('precompiled from forth/Forth Sources/08-editor.fs')
    colon('EDIT-LINE-CAP', [])
    dw(['doLIT', 160, 'EXIT'])
    colon('EDIT-REC-SIZE', [])
    dw(['doLIT', 164, 'EXIT'])
    colon('EDIT-ARENA-SIZE', [])
    dw(['doLIT', 8192, 'EXIT'])
    colon('EDIT-TEXT-W', [])
    dw(['doLIT', 80, 'EXIT'])
    colon('EDIT-TEXT-H', [])
    dw(['doLIT', 23, 'EXIT'])
    colon('EDIT-STATUS-ROW', [])
    dw(['doLIT', 24, 'EXIT'])
    colon('EDIT-HELP-ROW', [])
    dw(['doLIT', 25, 'EXIT'])
    colon('EDIT-MSG-NONE', [])
    dw(['doLIT', 0, 'EXIT'])
    colon('EDIT-MSG-SAVED', [])
    dw(['doLIT', 1, 'EXIT'])
    colon('EDIT-MSG-BUFFER', [])
    dw(['doLIT', 2, 'EXIT'])
    colon('EDIT-MSG-LONG', [])
    dw(['doLIT', 3, 'EXIT'])
    colon('EDIT-MSG-OPEN', [])
    dw(['doLIT', 4, 'EXIT'])
    colon('EDIT-MSG-READ', [])
    dw(['doLIT', 5, 'EXIT'])
    colon('EDIT-MSG-WRITE', [])
    dw(['doLIT', 6, 'EXIT'])
    colon('EDIT-MSG-NEW', [])
    dw(['doLIT', 7, 'EXIT'])
    colon('EDIT-MSG-NAME', [])
    dw(['doLIT', 8, 'EXIT'])
    colon('EDIT-MSG-UNSUP', [])
    dw(['doLIT', 9, 'EXIT'])
    colon('EDIT-USER-OFFSET', [])
    dw(['doLIT', 256, 'EXIT'])
    colon('EDIT-PATH-SIZE', [])
    dw(['doLIT', 260, 'EXIT'])
    if asm._USER < 256 * asm.CELLL:
        skip_user(256 - (asm._USER // asm.CELLL))
    elif asm._USER > 256 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-MARK')
    user('EDIT-MARK')
    if asm._USER < 257 * asm.CELLL:
        skip_user(257 - (asm._USER // asm.CELLL))
    elif asm._USER > 257 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-BASE')
    user('EDIT-BASE')
    if asm._USER < 258 * asm.CELLL:
        skip_user(258 - (asm._USER // asm.CELLL))
    elif asm._USER > 258 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-HERE')
    user('EDIT-HERE')
    if asm._USER < 259 * asm.CELLL:
        skip_user(259 - (asm._USER // asm.CELLL))
    elif asm._USER > 259 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-LIMIT')
    user('EDIT-LIMIT')
    if asm._USER < 260 * asm.CELLL:
        skip_user(260 - (asm._USER // asm.CELLL))
    elif asm._USER > 260 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-FREE')
    user('EDIT-FREE')
    if asm._USER < 261 * asm.CELLL:
        skip_user(261 - (asm._USER // asm.CELLL))
    elif asm._USER > 261 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-HEAD')
    user('EDIT-HEAD')
    if asm._USER < 262 * asm.CELLL:
        skip_user(262 - (asm._USER // asm.CELLL))
    elif asm._USER > 262 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-TAIL')
    user('EDIT-TAIL')
    if asm._USER < 263 * asm.CELLL:
        skip_user(263 - (asm._USER // asm.CELLL))
    elif asm._USER > 263 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-CUR')
    user('EDIT-CUR')
    if asm._USER < 264 * asm.CELLL:
        skip_user(264 - (asm._USER // asm.CELLL))
    elif asm._USER > 264 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-TOP')
    user('EDIT-TOP')
    if asm._USER < 265 * asm.CELLL:
        skip_user(265 - (asm._USER // asm.CELLL))
    elif asm._USER > 265 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-LINES')
    user('EDIT-LINES')
    if asm._USER < 266 * asm.CELLL:
        skip_user(266 - (asm._USER // asm.CELLL))
    elif asm._USER > 266 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-CUR#')
    user('EDIT-CUR#')
    if asm._USER < 267 * asm.CELLL:
        skip_user(267 - (asm._USER // asm.CELLL))
    elif asm._USER > 267 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-TOP#')
    user('EDIT-TOP#')
    if asm._USER < 268 * asm.CELLL:
        skip_user(268 - (asm._USER // asm.CELLL))
    elif asm._USER > 268 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-COL')
    user('EDIT-COL')
    if asm._USER < 269 * asm.CELLL:
        skip_user(269 - (asm._USER // asm.CELLL))
    elif asm._USER > 269 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-PREF')
    user('EDIT-PREF')
    if asm._USER < 270 * asm.CELLL:
        skip_user(270 - (asm._USER // asm.CELLL))
    elif asm._USER > 270 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-MODIFIED')
    user('EDIT-MODIFIED')
    if asm._USER < 271 * asm.CELLL:
        skip_user(271 - (asm._USER // asm.CELLL))
    elif asm._USER > 271 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-INSERT')
    user('EDIT-INSERT')
    if asm._USER < 272 * asm.CELLL:
        skip_user(272 - (asm._USER // asm.CELLL))
    elif asm._USER > 272 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-RUNNING')
    user('EDIT-RUNNING')
    if asm._USER < 273 * asm.CELLL:
        skip_user(273 - (asm._USER // asm.CELLL))
    elif asm._USER > 273 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-MSG')
    user('EDIT-MSG')
    if asm._USER < 274 * asm.CELLL:
        skip_user(274 - (asm._USER // asm.CELLL))
    elif asm._USER > 274 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-PATH-LEN')
    user('EDIT-PATH-LEN')
    if asm._USER < 275 * asm.CELLL:
        skip_user(275 - (asm._USER // asm.CELLL))
    elif asm._USER > 275 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-PATH-BUF#')
    user('EDIT-PATH-BUF#')
    if asm._USER < 276 * asm.CELLL:
        skip_user(276 - (asm._USER // asm.CELLL))
    elif asm._USER > 276 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-CLIP-LEN')
    user('EDIT-CLIP-LEN')
    if asm._USER < 277 * asm.CELLL:
        skip_user(277 - (asm._USER // asm.CELLL))
    elif asm._USER > 277 * asm.CELLL:
        raise RuntimeError('USER offset overlap for EDIT-CLIP-BUF#')
    user('EDIT-CLIP-BUF#')
    if asm._USER < 278 * asm.CELLL:
        skip_user(278 - (asm._USER // asm.CELLL))
    elif asm._USER > 278 * asm.CELLL:
        raise RuntimeError('USER offset overlap for ET1')
    user('ET1')
    if asm._USER < 279 * asm.CELLL:
        skip_user(279 - (asm._USER // asm.CELLL))
    elif asm._USER > 279 * asm.CELLL:
        raise RuntimeError('USER offset overlap for ET2')
    user('ET2')
    if asm._USER < 280 * asm.CELLL:
        skip_user(280 - (asm._USER // asm.CELLL))
    elif asm._USER > 280 * asm.CELLL:
        raise RuntimeError('USER offset overlap for ET3')
    user('ET3')
    if asm._USER < 281 * asm.CELLL:
        skip_user(281 - (asm._USER // asm.CELLL))
    elif asm._USER > 281 * asm.CELLL:
        raise RuntimeError('USER offset overlap for ET4')
    user('ET4')
    colon('EDIT-LINE-NEXT', [])
    dw(['EXIT'])
    colon('EDIT-LINE-PREV', [])
    dw(['1+', 'EXIT'])
    colon('EDIT-LINE-LEN', [])
    dw(['doLIT', 2, '+', 'EXIT'])
    colon('EDIT-LINE-FLAGS', [])
    dw(['doLIT', 3, '+', 'EXIT'])
    colon('EDIT-LINE-TEXT', [])
    dw(['doLIT', 4, '+', 'EXIT'])
    colon('EDIT-LINE-LEN@', [])
    dw(['EDIT-LINE-LEN', '@', 'EXIT'])
    colon('EDIT-LINE-LEN!', [])
    dw(['EDIT-LINE-LEN', '!', 'EXIT'])
    colon('EDIT-LINE-ADDR', [])
    dw(['SWAP', 'EDIT-LINE-TEXT', '+', 'EXIT'])
    colon('EDIT-PATH-BUF', [])
    dw(['EDIT-PATH-BUF#', '@', 'EXIT'])
    colon('EDIT-CLIP-BUF', [])
    dw(['EDIT-CLIP-BUF#', '@', 'EXIT'])
    colon('EDIT-PATH$', [])
    dw(['EDIT-PATH-BUF', 'EDIT-PATH-LEN', '@', 'EXIT'])
    colon('EDIT-PATH!', [])
    dw(['DUP', 'EDIT-PATH-LEN', '!', 'EDIT-PATH-BUF', 'SWAP', 'CMOVE', 'EXIT'])
    colon('EDIT-MSG!', [])
    dw(['EDIT-MSG', '!', 'EXIT'])
    colon('EDIT-CUR-LEN', [])
    dw(['EDIT-CUR', '@', 'EDIT-LINE-LEN@', 'EXIT'])
    colon('EDIT-CUR-ADDR', [])
    dw(['EDIT-CUR', '@', 'EDIT-LINE-TEXT', 'EXIT'])
    colon('EDIT-LINE-COUNT', [])
    dw(['EDIT-LINES', '@', 'EXIT'])
    colon('EDIT-COL!', [])
    dw(['DUP', 'EDIT-COL', '!', 'EDIT-PREF', '!', 'EXIT'])
    colon('EDIT-CLEAR-LINE', [])
    dw(['doLIT', 0, 'OVER', 'EDIT-LINE-LEN', '!', 'DROP', 'EXIT'])
    colon('ED-ALLOC', [])
    dw(['EDIT-FREE', '@', '?DUP', '?branch', 'PC_08_2Deditor_ED_2DALLOC_IF_FALSE_1', 'DUP', '@', 'EDIT-FREE', '!', 'branch', 'PC_08_2Deditor_ED_2DALLOC_IF_END_2'])
    label('PC_08_2Deditor_ED_2DALLOC_IF_FALSE_1')
    dw(['EDIT-HERE', '@', 'DUP', 'EDIT-REC-SIZE', '+', 'EDIT-LIMIT', '@', 'SWAP', 'U<', '?branch', 'PC_08_2Deditor_ED_2DALLOC_IF_FALSE_3', 'DROP', 'doLIT', 0, 'EXIT'])
    label('PC_08_2Deditor_ED_2DALLOC_IF_FALSE_3')
    dw(['DUP', 'EDIT-REC-SIZE', '+', 'EDIT-HERE', '!'])
    label('PC_08_2Deditor_ED_2DALLOC_IF_END_2')
    dw(['DUP', 'doLIT', 0, 'OVER', '!', 'SWAP', 'DROP', 'DUP', 'EDIT-LINE-PREV', 'doLIT', 0, 'SWAP', '!', 'DUP', 'EDIT-LINE-LEN', 'doLIT', 0, 'SWAP', '!', 'DUP', 'EDIT-LINE-FLAGS', 'doLIT', 0, 'SWAP', '!', 'EXIT'])
    colon('EDIT-FREE-LINE', [])
    dw(['EDIT-FREE', '@', 'OVER', '!', 'EDIT-FREE', '!', 'EXIT'])
    colon('EDIT-LINK-AFTER', [])
    dw(['ET1', '!', 'ET2', '!', 'ET1', '@', '@', 'ET2', '@', '!', 'ET1', '@', 'ET2', '@', 'EDIT-LINE-PREV', '!', 'ET2', '@', '@', '?DUP', '?branch', 'PC_08_2Deditor_EDIT_2DLINK_2DAFTER_IF_FALSE_1', 'ET2', '@', 'SWAP', 'EDIT-LINE-PREV', '!', 'branch', 'PC_08_2Deditor_EDIT_2DLINK_2DAFTER_IF_END_2'])
    label('PC_08_2Deditor_EDIT_2DLINK_2DAFTER_IF_FALSE_1')
    dw(['ET1', '@', 'EDIT-TAIL', '!'])
    label('PC_08_2Deditor_EDIT_2DLINK_2DAFTER_IF_END_2')
    dw(['ET1', '@', 'ET2', '@', '!', 'EXIT'])
    colon('EDIT-UNLINK', [])
    dw(['DUP', '@', 'ET1', '!', 'DUP', 'EDIT-LINE-PREV', '@', 'ET2', '!', 'ET2', '@', '?branch', 'PC_08_2Deditor_EDIT_2DUNLINK_IF_FALSE_1', 'ET1', '@', 'ET2', '@', '!', 'branch', 'PC_08_2Deditor_EDIT_2DUNLINK_IF_END_2'])
    label('PC_08_2Deditor_EDIT_2DUNLINK_IF_FALSE_1')
    dw(['ET1', '@', 'EDIT-HEAD', '!'])
    label('PC_08_2Deditor_EDIT_2DUNLINK_IF_END_2')
    dw(['ET1', '@', '?branch', 'PC_08_2Deditor_EDIT_2DUNLINK_IF_FALSE_3', 'ET2', '@', 'ET1', '@', 'EDIT-LINE-PREV', '!', 'branch', 'PC_08_2Deditor_EDIT_2DUNLINK_IF_END_4'])
    label('PC_08_2Deditor_EDIT_2DUNLINK_IF_FALSE_3')
    dw(['ET2', '@', 'EDIT-TAIL', '!'])
    label('PC_08_2Deditor_EDIT_2DUNLINK_IF_END_4')
    dw(['EXIT'])
    colon('EDIT-RESET-BUFFER', [])
    dw(['doLIT', 0, 'EDIT-FREE', '!', 'EDIT-BASE', '@', 'EDIT-HERE', '!', 'doLIT', 0, 'EDIT-MODIFIED', '!', 'doLIT', 0, 'EDIT-MSG', '!', 'doLIT', 0, 'EDIT-COL', '!', 'doLIT', 0, 'EDIT-PREF', '!', 'doLIT', 0, 'EDIT-CLIP-LEN', '!', 'ED-ALLOC', 'DUP', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DRESET_2DBUFFER_IF_FALSE_1', 'DROP', 'EDIT-MSG-BUFFER', 'EDIT-MSG', '!', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DRESET_2DBUFFER_IF_FALSE_1')
    dw(['DUP', 'EDIT-HEAD', '!', 'DUP', 'EDIT-TAIL', '!', 'DUP', 'EDIT-CUR', '!', 'DUP', 'EDIT-TOP', '!', 'DROP', 'doLIT', 1, 'EDIT-LINES', '!', 'doLIT', 1, 'EDIT-CUR#', '!', 'doLIT', 1, 'EDIT-TOP#', '!', 'EXIT'])
    colon('EDIT-INIT', [])
    dw(['CP', '@', 'EDIT-MARK', '!', 'CP', '@', 'DUP', 'EDIT-PATH-BUF#', '!', 'EDIT-PATH-SIZE', '+', 'DUP', 'EDIT-CLIP-BUF#', '!', 'EDIT-LINE-CAP', '+', 'DUP', 'EDIT-BASE', '!', 'DUP', 'EDIT-HERE', '!', 'EDIT-ARENA-SIZE', '+', 'EDIT-LIMIT', '!', 'EDIT-LIMIT', '@', 'CP', '!', 'doLIT', 1, 'EDIT-INSERT', '!', 'EDIT-MSG-NONE', 'EDIT-MSG', '!', 'doLIT', 0, 'EDIT-PATH-LEN', '!', 'EDIT-RESET-BUFFER', 'EXIT'])
    colon('EDIT-DONE', [])
    dw(['EDIT-MARK', '@', 'CP', '!', 'NORMAL', 'CURSOR-ON', 'EXIT'])
    colon('EDIT-TRIM-LEN', [])
    dw(['DUP', 'EDIT-LINE-LEN@', 'ET1', '!'])
    label('PC_08_2Deditor_EDIT_2DTRIM_2DLEN_BEGIN_1')
    dw(['ET1', '@', '?branch', 'PC_08_2Deditor_EDIT_2DTRIM_2DLEN_WHILE_END_2', 'DUP', 'EDIT-LINE-TEXT', 'ET1', '@', '1-', '+', 'C@', 'BL', '=', '?branch', 'PC_08_2Deditor_EDIT_2DTRIM_2DLEN_IF_FALSE_3', 'ET1', '@', '1-', 'ET1', '!', 'branch', 'PC_08_2Deditor_EDIT_2DTRIM_2DLEN_IF_END_4'])
    label('PC_08_2Deditor_EDIT_2DTRIM_2DLEN_IF_FALSE_3')
    dw(['DROP', 'ET1', '@', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DTRIM_2DLEN_IF_END_4')
    dw(['branch', 'PC_08_2Deditor_EDIT_2DTRIM_2DLEN_BEGIN_1'])
    label('PC_08_2Deditor_EDIT_2DTRIM_2DLEN_WHILE_END_2')
    dw(['DROP', 'doLIT', 0, 'EXIT'])
    colon('EDIT-EXTEND-CUR', [])
    dw(['DUP', 'EDIT-LINE-CAP', '>', '?branch', 'PC_08_2Deditor_EDIT_2DEXTEND_2DCUR_IF_FALSE_1', 'DROP', 'EDIT-MSG-LONG', 'EDIT-MSG', '!', 'doLIT', 0, 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DEXTEND_2DCUR_IF_FALSE_1')
    dw(['DUP', 'EDIT-CUR-LEN', '<=', '?branch', 'PC_08_2Deditor_EDIT_2DEXTEND_2DCUR_IF_FALSE_2', 'DROP', 'doLIT', -1, 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DEXTEND_2DCUR_IF_FALSE_2')
    dw(['DUP', 'ET1', '!', 'EDIT-CUR-LEN', 'ET2', '!', 'EDIT-CUR', '@', 'EDIT-LINE-TEXT', 'ET2', '@', '+', 'ET1', '@', 'ET2', '@', '-', 'BL', 'FILL', 'ET1', '@', 'EDIT-CUR', '@', 'EDIT-LINE-LEN', '!', 'DROP', 'doLIT', -1, 'EXIT'])
    colon('EDIT-ENSURE-VISIBLE', [])
    label('PC_08_2Deditor_EDIT_2DENSURE_2DVISIBLE_BEGIN_1')
    dw(['EDIT-CUR#', '@', 'EDIT-TOP#', '@', '<', '?branch', 'PC_08_2Deditor_EDIT_2DENSURE_2DVISIBLE_WHILE_END_2', 'EDIT-TOP', '@', 'EDIT-LINE-PREV', '@', 'EDIT-TOP', '!', 'EDIT-TOP#', '@', '1-', 'EDIT-TOP#', '!', 'branch', 'PC_08_2Deditor_EDIT_2DENSURE_2DVISIBLE_BEGIN_1'])
    label('PC_08_2Deditor_EDIT_2DENSURE_2DVISIBLE_WHILE_END_2')
    label('PC_08_2Deditor_EDIT_2DENSURE_2DVISIBLE_BEGIN_3')
    dw(['EDIT-CUR#', '@', 'EDIT-TOP#', '@', 'EDIT-TEXT-H', '+', '>=', '?branch', 'PC_08_2Deditor_EDIT_2DENSURE_2DVISIBLE_WHILE_END_4', 'EDIT-TOP', '@', '@', 'EDIT-TOP', '!', 'EDIT-TOP#', '@', '1+', 'EDIT-TOP#', '!', 'branch', 'PC_08_2Deditor_EDIT_2DENSURE_2DVISIBLE_BEGIN_3'])
    label('PC_08_2Deditor_EDIT_2DENSURE_2DVISIBLE_WHILE_END_4')
    dw(['EXIT'])
    colon('EDIT-MOVE-UP', [])
    dw(['EDIT-CUR', '@', 'EDIT-LINE-PREV', '@', '?DUP', '?branch', 'PC_08_2Deditor_EDIT_2DMOVE_2DUP_IF_FALSE_1', 'EDIT-CUR', '!', 'EDIT-CUR#', '@', '1-', 'EDIT-CUR#', '!', 'EDIT-PREF', '@', 'EDIT-COL', '!', 'EDIT-ENSURE-VISIBLE'])
    label('PC_08_2Deditor_EDIT_2DMOVE_2DUP_IF_FALSE_1')
    dw(['EXIT'])
    colon('EDIT-MOVE-DOWN', [])
    dw(['EDIT-CUR', '@', '@', '?DUP', '?branch', 'PC_08_2Deditor_EDIT_2DMOVE_2DDOWN_IF_FALSE_1', 'EDIT-CUR', '!', 'EDIT-CUR#', '@', '1+', 'EDIT-CUR#', '!', 'EDIT-PREF', '@', 'EDIT-COL', '!', 'EDIT-ENSURE-VISIBLE'])
    label('PC_08_2Deditor_EDIT_2DMOVE_2DDOWN_IF_FALSE_1')
    dw(['EXIT'])
    colon('EDIT-MOVE-LEFT', [])
    dw(['EDIT-COL', '@', '?branch', 'PC_08_2Deditor_EDIT_2DMOVE_2DLEFT_IF_FALSE_1', 'EDIT-COL', '@', '1-', 'EDIT-COL', '!', 'EDIT-COL', '@', 'EDIT-PREF', '!'])
    label('PC_08_2Deditor_EDIT_2DMOVE_2DLEFT_IF_FALSE_1')
    dw(['EXIT'])
    colon('EDIT-MOVE-RIGHT', [])
    dw(['EDIT-COL', '@', '1+', 'DUP', 'EDIT-COL', '!', 'EDIT-PREF', '!', 'EXIT'])
    colon('EDIT-MOVE-HOME', [])
    dw(['doLIT', 0, 'EDIT-COL!', 'EXIT'])
    colon('EDIT-MOVE-END', [])
    dw(['EDIT-CUR-LEN', 'EDIT-COL!', 'EXIT'])
    colon('EDIT-PAGE-UP', [])
    dw(['doLIT', 0, 'ET1', '!'])
    label('PC_08_2Deditor_EDIT_2DPAGE_2DUP_BEGIN_1')
    dw(['ET1', '@', 'EDIT-TEXT-H', '<', '?branch', 'PC_08_2Deditor_EDIT_2DPAGE_2DUP_WHILE_END_2', 'EDIT-MOVE-UP', 'ET1', '@', '1+', 'ET1', '!', 'branch', 'PC_08_2Deditor_EDIT_2DPAGE_2DUP_BEGIN_1'])
    label('PC_08_2Deditor_EDIT_2DPAGE_2DUP_WHILE_END_2')
    dw(['EXIT'])
    colon('EDIT-PAGE-DOWN', [])
    dw(['doLIT', 0, 'ET1', '!'])
    label('PC_08_2Deditor_EDIT_2DPAGE_2DDOWN_BEGIN_1')
    dw(['ET1', '@', 'EDIT-TEXT-H', '<', '?branch', 'PC_08_2Deditor_EDIT_2DPAGE_2DDOWN_WHILE_END_2', 'EDIT-MOVE-DOWN', 'ET1', '@', '1+', 'ET1', '!', 'branch', 'PC_08_2Deditor_EDIT_2DPAGE_2DDOWN_BEGIN_1'])
    label('PC_08_2Deditor_EDIT_2DPAGE_2DDOWN_WHILE_END_2')
    dw(['EXIT'])
    colon('EDIT-SET-MODIFIED', [])
    dw(['doLIT', -1, 'EDIT-MODIFIED', '!', 'EDIT-MSG-NONE', 'EDIT-MSG', '!', 'EXIT'])
    colon('EDIT-OVERWRITE-CHAR', [])
    dw(['EDIT-COL', '@', '1+', 'EDIT-EXTEND-CUR', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DOVERWRITE_2DCHAR_IF_FALSE_1', 'DROP', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DOVERWRITE_2DCHAR_IF_FALSE_1')
    dw(['EDIT-COL', '@', 'EDIT-CUR', '@', 'EDIT-LINE-ADDR', 'C!', 'EDIT-COL', '@', '1+', 'EDIT-COL!', 'EDIT-SET-MODIFIED', 'EXIT'])
    colon('EDIT-INSERT-CHAR', [])
    dw(['EDIT-COL', '@', 'ET3', '!', 'EDIT-CUR-LEN', 'ET4', '!', 'ET3', '@', 'ET4', '@', '>=', '?branch', 'PC_08_2Deditor_EDIT_2DINSERT_2DCHAR_IF_FALSE_1', 'ET3', '@', '1+', 'EDIT-EXTEND-CUR', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DINSERT_2DCHAR_IF_FALSE_2', 'DROP', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DINSERT_2DCHAR_IF_FALSE_2')
    dw(['EDIT-COL', '@', 'EDIT-CUR', '@', 'EDIT-LINE-ADDR', 'C!', 'branch', 'PC_08_2Deditor_EDIT_2DINSERT_2DCHAR_IF_END_3'])
    label('PC_08_2Deditor_EDIT_2DINSERT_2DCHAR_IF_FALSE_1')
    dw(['ET4', '@', '1+', 'EDIT-EXTEND-CUR', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DINSERT_2DCHAR_IF_FALSE_4', 'DROP', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DINSERT_2DCHAR_IF_FALSE_4')
    dw(['ET3', '@', 'EDIT-CUR', '@', 'EDIT-LINE-ADDR', 'DUP', '1+', 'SWAP', 'ET4', '@', 'ET3', '@', '-', 'CMOVE>', 'EDIT-COL', '@', 'EDIT-CUR', '@', 'EDIT-LINE-ADDR', 'C!'])
    label('PC_08_2Deditor_EDIT_2DINSERT_2DCHAR_IF_END_3')
    dw(['EDIT-COL', '@', '1+', 'EDIT-COL!', 'EDIT-SET-MODIFIED', 'EXIT'])
    colon('EDIT-JOIN-NEXT', [])
    dw(['EDIT-CUR', '@', '@', '?DUP', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DJOIN_2DNEXT_IF_FALSE_1', 'DROP', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DJOIN_2DNEXT_IF_FALSE_1')
    dw(['DUP', 'ET1', '!', 'EDIT-CUR-LEN', 'ET2', '!', 'ET1', '@', 'EDIT-LINE-LEN@', 'ET3', '!', 'ET2', '@', 'ET3', '@', '+', 'EDIT-LINE-CAP', '>', '?branch', 'PC_08_2Deditor_EDIT_2DJOIN_2DNEXT_IF_FALSE_2', 'EDIT-MSG-LONG', 'EDIT-MSG', '!', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DJOIN_2DNEXT_IF_FALSE_2')
    dw(['ET1', '@', 'EDIT-LINE-TEXT', 'EDIT-CUR', '@', 'EDIT-LINE-TEXT', 'ET2', '@', '+', 'ET3', '@', 'CMOVE', 'ET2', '@', 'ET3', '@', '+', 'EDIT-CUR', '@', 'EDIT-LINE-LEN', '!', 'ET1', '@', 'EDIT-UNLINK', 'ET1', '@', 'EDIT-FREE-LINE', 'EDIT-LINES', '@', '1-', 'EDIT-LINES', '!', 'EDIT-SET-MODIFIED', 'EXIT'])
    colon('EDIT-DELETE-CHAR', [])
    dw(['EDIT-COL', '@', 'ET1', '!', 'EDIT-CUR-LEN', 'ET2', '!', 'ET1', '@', 'ET2', '@', '<', '?branch', 'PC_08_2Deditor_EDIT_2DDELETE_2DCHAR_IF_FALSE_1', 'EDIT-CUR', '@', 'ET1', '@', '1+', 'EDIT-LINE-ADDR', 'EDIT-CUR', '@', 'ET1', '@', 'EDIT-LINE-ADDR', 'ET2', '@', 'ET1', '@', '-', '1-', 'CMOVE', 'ET2', '@', '1-', 'EDIT-CUR', '@', 'EDIT-LINE-LEN', '!', 'EDIT-SET-MODIFIED', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DDELETE_2DCHAR_IF_FALSE_1')
    dw(['ET1', '@', 'ET2', '@', '=', '?branch', 'PC_08_2Deditor_EDIT_2DDELETE_2DCHAR_IF_FALSE_2', 'EDIT-JOIN-NEXT'])
    label('PC_08_2Deditor_EDIT_2DDELETE_2DCHAR_IF_FALSE_2')
    dw(['EXIT'])
    colon('EDIT-SPLIT-LINE', [])
    dw(['ED-ALLOC', 'DUP', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DSPLIT_2DLINE_IF_FALSE_1', 'DROP', 'EDIT-MSG-BUFFER', 'EDIT-MSG', '!', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DSPLIT_2DLINE_IF_FALSE_1')
    dw(['DUP', 'ET1', '!', 'EDIT-CUR', '@', 'ET2', '!', 'EDIT-COL', '@', 'ET3', '!', 'ET2', '@', 'EDIT-LINE-LEN@', 'ET4', '!', 'ET3', '@', 'ET4', '@', '<', '?branch', 'PC_08_2Deditor_EDIT_2DSPLIT_2DLINE_IF_FALSE_2', 'ET4', '@', 'ET3', '@', '-', 'DUP', 'ET1', '@', 'EDIT-LINE-LEN', '!', 'ET2', '@', 'EDIT-LINE-TEXT', 'ET3', '@', '+', 'ET1', '@', 'EDIT-LINE-TEXT', 'ROT', 'CMOVE', 'ET3', '@', 'ET2', '@', 'EDIT-LINE-LEN', '!', 'branch', 'PC_08_2Deditor_EDIT_2DSPLIT_2DLINE_IF_END_3'])
    label('PC_08_2Deditor_EDIT_2DSPLIT_2DLINE_IF_FALSE_2')
    dw(['doLIT', 0, 'ET1', '@', 'EDIT-LINE-LEN', '!'])
    label('PC_08_2Deditor_EDIT_2DSPLIT_2DLINE_IF_END_3')
    dw(['ET1', '@', 'ET2', '@', 'EDIT-LINK-AFTER', 'EDIT-LINES', '@', '1+', 'EDIT-LINES', '!', 'ET1', '@', 'EDIT-CUR', '!', 'EDIT-CUR#', '@', '1+', 'EDIT-CUR#', '!', 'doLIT', 0, 'EDIT-COL!', 'EDIT-ENSURE-VISIBLE', 'EDIT-SET-MODIFIED', 'EXIT'])
    colon('EDIT-BACKSPACE', [])
    dw(['EDIT-COL', '@', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DBACKSPACE_IF_FALSE_1', 'EDIT-CUR', '@', 'EDIT-LINE-PREV', '@', '?DUP', '?branch', 'PC_08_2Deditor_EDIT_2DBACKSPACE_IF_FALSE_2', 'DUP', 'EDIT-LINE-LEN@', 'ET1', '!', 'EDIT-CUR', '!', 'EDIT-CUR#', '@', '1-', 'EDIT-CUR#', '!', 'ET1', '@', 'EDIT-COL!', 'EDIT-JOIN-NEXT', 'EDIT-ENSURE-VISIBLE'])
    label('PC_08_2Deditor_EDIT_2DBACKSPACE_IF_FALSE_2')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2DBACKSPACE_IF_FALSE_1')
    dw(['EDIT-COL', '@', '1-', 'DUP', 'EDIT-COL', '!', 'EDIT-PREF', '!', 'EDIT-COL', '@', 'EDIT-CUR-LEN', '>=', '?branch', 'PC_08_2Deditor_EDIT_2DBACKSPACE_IF_FALSE_3', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DBACKSPACE_IF_FALSE_3')
    dw(['EDIT-DELETE-CHAR', 'EXIT'])
    colon('EDIT-DELETE-LINE', [])
    dw(['EDIT-LINES', '@', 'doLIT', 1, '=', '?branch', 'PC_08_2Deditor_EDIT_2DDELETE_2DLINE_IF_FALSE_1', 'EDIT-CUR', '@', 'EDIT-CLEAR-LINE', 'doLIT', 0, 'EDIT-COL!', 'EDIT-SET-MODIFIED', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DDELETE_2DLINE_IF_FALSE_1')
    dw(['EDIT-CUR', '@', 'ET1', '!', 'ET1', '@', '@', '?DUP', '?branch', 'PC_08_2Deditor_EDIT_2DDELETE_2DLINE_IF_FALSE_2', 'DUP', 'EDIT-CUR', '!', 'branch', 'PC_08_2Deditor_EDIT_2DDELETE_2DLINE_IF_END_3'])
    label('PC_08_2Deditor_EDIT_2DDELETE_2DLINE_IF_FALSE_2')
    dw(['ET1', '@', 'EDIT-LINE-PREV', '@', 'DUP', 'EDIT-CUR', '!', 'EDIT-CUR#', '@', '1-', 'EDIT-CUR#', '!'])
    label('PC_08_2Deditor_EDIT_2DDELETE_2DLINE_IF_END_3')
    dw(['ET1', '@', 'EDIT-TOP', '@', '=', '?branch', 'PC_08_2Deditor_EDIT_2DDELETE_2DLINE_IF_FALSE_4', 'EDIT-CUR', '@', 'EDIT-TOP', '!', 'EDIT-CUR#', '@', 'EDIT-TOP#', '!'])
    label('PC_08_2Deditor_EDIT_2DDELETE_2DLINE_IF_FALSE_4')
    dw(['ET1', '@', 'EDIT-UNLINK', 'ET1', '@', 'EDIT-FREE-LINE', 'EDIT-LINES', '@', '1-', 'EDIT-LINES', '!', 'EDIT-CUR-LEN', 'EDIT-COL', '@', 'MIN', 'EDIT-COL!', 'EDIT-ENSURE-VISIBLE', 'EDIT-SET-MODIFIED', 'EXIT'])
    colon('EDIT-COPY-LINE', [])
    dw(['EDIT-CUR', '@', 'EDIT-LINE-LEN@', 'DUP', 'EDIT-CLIP-LEN', '!', 'EDIT-CUR', '@', 'EDIT-LINE-TEXT', 'EDIT-CLIP-BUF', 'ROT', 'CMOVE', 'EDIT-MSG-NONE', 'EDIT-MSG', '!', 'EXIT'])
    colon('EDIT-PASTE-LINE', [])
    dw(['ED-ALLOC', 'DUP', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DPASTE_2DLINE_IF_FALSE_1', 'DROP', 'EDIT-MSG-BUFFER', 'EDIT-MSG', '!', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DPASTE_2DLINE_IF_FALSE_1')
    dw(['DUP', 'ET1', '!', 'EDIT-CLIP-LEN', '@', 'DUP', 'ET1', '@', 'EDIT-LINE-LEN', '!', 'EDIT-CLIP-BUF', 'ET1', '@', 'EDIT-LINE-TEXT', 'ROT', 'CMOVE', 'ET1', '@', 'EDIT-CUR', '@', 'EDIT-LINK-AFTER', 'ET1', '@', 'EDIT-CUR', '!', 'EDIT-LINES', '@', '1+', 'EDIT-LINES', '!', 'EDIT-CUR#', '@', '1+', 'EDIT-CUR#', '!', 'doLIT', 0, 'EDIT-COL!', 'EDIT-ENSURE-VISIBLE', 'EDIT-SET-MODIFIED', 'EXIT'])
    colon('EDIT-NEW', [])
    dw(['EDIT-RESET-BUFFER', 'EDIT-MSG-NEW', 'EDIT-MSG', '!', 'EXIT'])
    colon('EDIT-LOAD', [])
    dw(['EDIT-PATH!', 'EDIT-RESET-BUFFER', 'EDIT-PATH$', 'R/O', 'OPEN-FILE', 'DUP', '?branch', 'PC_08_2Deditor_EDIT_2DLOAD_IF_FALSE_1', 'SWAP', 'DROP', 'EDIT-MSG-OPEN', 'EDIT-MSG', '!', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DLOAD_IF_FALSE_1')
    dw(['DROP', '>R', 'EDIT-HEAD', '@', 'ET2', '!', 'doLIT', -1, 'ET3', '!'])
    label('PC_08_2Deditor_EDIT_2DLOAD_BEGIN_2')
    dw(['TIB', 'EDIT-LINE-CAP', 'R@', 'READ-LINE', 'DUP', '?branch', 'PC_08_2Deditor_EDIT_2DLOAD_IF_FALSE_3', 'DROP', 'DROP', 'DROP', 'R>', 'CLOSE-FILE', 'DROP', 'EDIT-MSG-READ', 'EDIT-MSG', '!', 'doLIT', 1, 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DLOAD_IF_FALSE_3')
    dw(['DROP', '?branch', 'PC_08_2Deditor_EDIT_2DLOAD_WHILE_END_4', 'ET3', '@', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DLOAD_IF_FALSE_5', 'ED-ALLOC', 'DUP', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DLOAD_IF_FALSE_6', 'DROP', 'R>', 'CLOSE-FILE', 'DROP', 'EDIT-MSG-BUFFER', 'EDIT-MSG', '!', 'doLIT', 2, 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DLOAD_IF_FALSE_6')
    dw(['DUP', 'EDIT-TAIL', '@', 'EDIT-LINK-AFTER', 'DUP', 'ET2', '!', 'EDIT-LINES', '@', '1+', 'EDIT-LINES', '!', 'DROP', 'branch', 'PC_08_2Deditor_EDIT_2DLOAD_IF_END_7'])
    label('PC_08_2Deditor_EDIT_2DLOAD_IF_FALSE_5')
    dw(['doLIT', 0, 'ET3', '!'])
    label('PC_08_2Deditor_EDIT_2DLOAD_IF_END_7')
    dw(['DUP', 'ET2', '@', 'EDIT-LINE-LEN', '!', 'TIB', 'ET2', '@', 'EDIT-LINE-TEXT', 'ROT', 'CMOVE', 'branch', 'PC_08_2Deditor_EDIT_2DLOAD_BEGIN_2'])
    label('PC_08_2Deditor_EDIT_2DLOAD_WHILE_END_4')
    dw(['DROP', 'R>', 'CLOSE-FILE', 'DROP', 'EDIT-HEAD', '@', 'EDIT-CUR', '!', 'EDIT-HEAD', '@', 'EDIT-TOP', '!', 'doLIT', 1, 'EDIT-CUR#', '!', 'doLIT', 1, 'EDIT-TOP#', '!', 'doLIT', 0, 'EDIT-COL!', 'doLIT', 0, 'EDIT-MODIFIED', '!', 'EDIT-MSG-NONE', 'EDIT-MSG', '!', 'doLIT', 0, 'EXIT'])
    colon('EDIT-SAVE', [])
    dw(['EDIT-PATH-LEN', '@', '0=', '?branch', 'PC_08_2Deditor_EDIT_2DSAVE_IF_FALSE_1', 'EDIT-MSG-NAME', 'EDIT-MSG', '!', 'doLIT', 1, 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DSAVE_IF_FALSE_1')
    dw(['EDIT-PATH$', 'DELETE-FILE', 'DROP', 'EDIT-PATH$', 'R/W', 'CREATE-FILE', 'DUP', '?branch', 'PC_08_2Deditor_EDIT_2DSAVE_IF_FALSE_2', 'SWAP', 'DROP', 'EDIT-MSG-WRITE', 'EDIT-MSG', '!', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DSAVE_IF_FALSE_2')
    dw(['DROP', 'ET4', '!', 'EDIT-HEAD', '@'])
    label('PC_08_2Deditor_EDIT_2DSAVE_BEGIN_3')
    dw(['DUP', '?branch', 'PC_08_2Deditor_EDIT_2DSAVE_WHILE_END_4', 'DUP', 'EDIT-TRIM-LEN', 'DUP', 'ET2', '!', 'OVER', 'EDIT-LINE-TEXT', 'ET2', '@', 'ET4', '@', 'WRITE-LINE', 'DUP', '?branch', 'PC_08_2Deditor_EDIT_2DSAVE_IF_FALSE_5', 'DROP', 'ET4', '@', 'CLOSE-FILE', 'DROP', 'EDIT-MSG-WRITE', 'EDIT-MSG', '!', 'doLIT', 1, 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DSAVE_IF_FALSE_5')
    dw(['DROP', '@', 'branch', 'PC_08_2Deditor_EDIT_2DSAVE_BEGIN_3'])
    label('PC_08_2Deditor_EDIT_2DSAVE_WHILE_END_4')
    dw(['DROP', 'ET4', '@', 'FLUSH-FILE', 'DROP', 'ET4', '@', 'CLOSE-FILE', 'DROP', 'doLIT', 0, 'EDIT-MODIFIED', '!', 'EDIT-MSG-SAVED', 'EDIT-MSG', '!', 'doLIT', 0, 'EXIT'])
    colon('EDIT-.MSG', [])
    dw(['EDIT-MSG', '@', 'DUP', 'EDIT-MSG-SAVED', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_1', 'DROP'])
    ds('."|', ' Saved')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_1')
    dw(['DUP', 'EDIT-MSG-BUFFER', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_2', 'DROP'])
    ds('."|', ' Buffer full')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_2')
    dw(['DUP', 'EDIT-MSG-LONG', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_3', 'DROP'])
    ds('."|', ' Line too long')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_3')
    dw(['DUP', 'EDIT-MSG-OPEN', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_4', 'DROP'])
    ds('."|', ' Open failed')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_4')
    dw(['DUP', 'EDIT-MSG-READ', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_5', 'DROP'])
    ds('."|', ' Read failed')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_5')
    dw(['DUP', 'EDIT-MSG-WRITE', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_6', 'DROP'])
    ds('."|', ' Write failed')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_6')
    dw(['DUP', 'EDIT-MSG-NEW', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_7', 'DROP'])
    ds('."|', ' New buffer')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_7')
    dw(['DUP', 'EDIT-MSG-NAME', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_8', 'DROP'])
    ds('."|', ' No filename')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_8')
    dw(['DUP', 'EDIT-MSG-UNSUP', '=', '?branch', 'PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_9', 'DROP'])
    ds('."|', ' Not in MVP')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2D_2EMSG_IF_FALSE_9')
    dw(['DROP', 'EXIT'])
    colon('EDIT-DRAW-ROW', [])
    dw(['ET1', '!', 'ET2', '!', 'doLIT', 1, 'ET1', '@', 'AT', 'CL-LINE', 'ET2', '@', '?DUP', '?branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DROW_IF_FALSE_1', 'ET2', '@', 'EDIT-LINE-LEN@', 'EDIT-TEXT-W', 'MIN', 'ET3', '!', 'doLIT', 0, 'ET4', '!'])
    label('PC_08_2Deditor_EDIT_2DDRAW_2DROW_BEGIN_2')
    dw(['ET4', '@', 'ET3', '@', '<', '?branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DROW_WHILE_END_3', 'ET2', '@', 'EDIT-LINE-TEXT', 'ET4', '@', '+', 'C@', 'EMIT', 'ET4', '@', '1+', 'ET4', '!', 'branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DROW_BEGIN_2'])
    label('PC_08_2Deditor_EDIT_2DDRAW_2DROW_WHILE_END_3')
    label('PC_08_2Deditor_EDIT_2DDRAW_2DROW_IF_FALSE_1')
    dw(['EXIT'])
    colon('EDIT-DRAW-TEXT', [])
    dw(['EDIT-TOP', '@', 'ET1', '!', 'doLIT', 1, 'ET2', '!'])
    label('PC_08_2Deditor_EDIT_2DDRAW_2DTEXT_BEGIN_1')
    dw(['ET2', '@', 'EDIT-TEXT-H', '<=', '?branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DTEXT_WHILE_END_2', 'ET1', '@', 'ET2', '@', 'EDIT-DRAW-ROW', 'ET1', '@', '?branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DTEXT_IF_FALSE_3', 'ET1', '@', '@', 'ET1', '!'])
    label('PC_08_2Deditor_EDIT_2DDRAW_2DTEXT_IF_FALSE_3')
    dw(['ET2', '@', '1+', 'ET2', '!', 'branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DTEXT_BEGIN_1'])
    label('PC_08_2Deditor_EDIT_2DDRAW_2DTEXT_WHILE_END_2')
    dw(['EXIT'])
    colon('EDIT-DRAW-STATUS', [])
    dw(['REVERSE', 'doLIT', 1, 'EDIT-STATUS-ROW', 'AT', 'CL-LINE', 'EDIT-PATH$', 'TYPE', 'EDIT-MODIFIED', '@', '?branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DSTATUS_IF_FALSE_1'])
    ds('."|', ' *')
    dw(['branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DSTATUS_IF_END_2'])
    label('PC_08_2Deditor_EDIT_2DDRAW_2DSTATUS_IF_FALSE_1')
    ds('."|', ' -')
    label('PC_08_2Deditor_EDIT_2DDRAW_2DSTATUS_IF_END_2')
    ds('."|', ' Ln ')
    dw(['EDIT-CUR#', '@', 'ANSI#'])
    ds('."|', ' Col ')
    dw(['EDIT-COL', '@', '1+', 'ANSI#', 'EDIT-INSERT', '@', '?branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DSTATUS_IF_FALSE_3'])
    ds('."|', ' INS')
    dw(['branch', 'PC_08_2Deditor_EDIT_2DDRAW_2DSTATUS_IF_END_4'])
    label('PC_08_2Deditor_EDIT_2DDRAW_2DSTATUS_IF_FALSE_3')
    ds('."|', ' OVR')
    label('PC_08_2Deditor_EDIT_2DDRAW_2DSTATUS_IF_END_4')
    dw(['EDIT-.MSG', 'NORMAL', 'EXIT'])
    colon('EDIT-DRAW-HELP', [])
    dw(['doLIT', 1, 'EDIT-HELP-ROW', 'AT', 'CL-LINE', 'NORMAL'])
    ds('."|', '1')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', '      ')
    dw(['NORMAL'])
    ds('."|', '2')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', 'Save  ')
    dw(['NORMAL'])
    ds('."|', '3')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', '      ')
    dw(['NORMAL'])
    ds('."|', '4')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', 'New   ')
    dw(['NORMAL'])
    ds('."|', '5')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', 'Copy  ')
    dw(['NORMAL'])
    ds('."|', '6')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', '      ')
    dw(['NORMAL'])
    ds('."|', '7')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', 'Paste ')
    dw(['NORMAL'])
    ds('."|', '8')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', 'DelLn ')
    dw(['NORMAL'])
    ds('."|', '9')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', '      ')
    dw(['NORMAL'])
    ds('."|', '10')
    dw(['HSL_CYAN', 'BG!', 'BLACK', 'FG!'])
    ds('."|', 'Exit  ')
    dw(['NORMAL', 'EXIT'])
    colon('EDIT-PLACE-CURSOR', [])
    dw(['EDIT-CUR#', '@', 'EDIT-TOP#', '@', '-', '1+', 'doLIT', 1, 'MAX', 'EDIT-TEXT-H', 'MIN', 'ET1', '!', 'EDIT-COL', '@', '1+', 'doLIT', 1, 'MAX', 'EDIT-TEXT-W', 'MIN', 'ET2', '!', 'ET2', '@', 'ET1', '@', 'AT', 'EXIT'])
    colon('EDIT-REDRAW', [])
    dw(['CURSOR-OFF', 'CLS', 'HOME', 'EDIT-DRAW-TEXT', 'EDIT-DRAW-STATUS', 'EDIT-DRAW-HELP', 'EDIT-PLACE-CURSOR', 'CURSOR-ON', 'EXIT'])
    colon('EDIT-HANDLE-PRINTABLE', [])
    dw(['DUP', 'doLIT', 32, 'doLIT', 127, 'WITHIN', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DPRINTABLE_IF_FALSE_1', 'EDIT-INSERT', '@', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DPRINTABLE_IF_FALSE_2', 'EDIT-INSERT-CHAR', 'branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DPRINTABLE_IF_END_3'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DPRINTABLE_IF_FALSE_2')
    dw(['EDIT-OVERWRITE-CHAR'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DPRINTABLE_IF_END_3')
    dw(['EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DPRINTABLE_IF_FALSE_1')
    dw(['DROP', 'EXIT'])
    colon('EDIT-HANDLE-CHAR', [])
    dw(['DUP', 'doLIT', 8, '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_1', 'DROP', 'EDIT-BACKSPACE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_1')
    dw(['DUP', 'doLIT', 127, '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_2', 'DROP', 'EDIT-BACKSPACE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_2')
    dw(['DUP', 'doLIT', 13, '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_3', 'DROP', 'EDIT-SPLIT-LINE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_3')
    dw(['DUP', 'doLIT', 10, '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_4', 'DROP', 'EDIT-SPLIT-LINE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_4')
    dw(['DUP', 'doLIT', 9, '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_5', 'DROP', 'BL', 'EDIT-HANDLE-PRINTABLE', 'BL', 'EDIT-HANDLE-PRINTABLE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DCHAR_IF_FALSE_5')
    dw(['EDIT-HANDLE-PRINTABLE', 'EXIT'])
    colon('EDIT-HANDLE-EKEY', [])
    dw(['DUP', 'KEY_LEFT', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_1', 'DROP', 'EDIT-MOVE-LEFT', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_1')
    dw(['DUP', 'KEY_RIGHT', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_2', 'DROP', 'EDIT-MOVE-RIGHT', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_2')
    dw(['DUP', 'KEY_UP', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_3', 'DROP', 'EDIT-MOVE-UP', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_3')
    dw(['DUP', 'KEY_DOWN', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_4', 'DROP', 'EDIT-MOVE-DOWN', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_4')
    dw(['DUP', 'KEY_HOME', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_5', 'DROP', 'EDIT-MOVE-HOME', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_5')
    dw(['DUP', 'KEY_END', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_6', 'DROP', 'EDIT-MOVE-END', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_6')
    dw(['DUP', 'KEY_PGUP', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_7', 'DROP', 'EDIT-PAGE-UP', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_7')
    dw(['DUP', 'KEY_PGDN', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_8', 'DROP', 'EDIT-PAGE-DOWN', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_8')
    dw(['DUP', 'KEY_BACKSPACE', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_9', 'DROP', 'EDIT-BACKSPACE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_9')
    dw(['DUP', 'KEY_DEL', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_10', 'DROP', 'EDIT-DELETE-CHAR', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_10')
    dw(['DUP', 'KEY_ENTER', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_11', 'DROP', 'EDIT-SPLIT-LINE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_11')
    dw(['DUP', 'KEY_INS', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_12', 'DROP', 'EDIT-INSERT', '@', '0=', 'EDIT-INSERT', '!', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_12')
    dw(['DUP', 'KEY_F2', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_13', 'DROP', 'EDIT-SAVE', 'DROP', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_13')
    dw(['DUP', 'KEY_F4', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_14', 'DROP', 'EDIT-NEW', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_14')
    dw(['DUP', 'KEY_F5', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_15', 'DROP', 'EDIT-COPY-LINE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_15')
    dw(['DUP', 'KEY_F7', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_16', 'DROP', 'EDIT-PASTE-LINE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_16')
    dw(['DUP', 'KEY_F8', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_17', 'DROP', 'EDIT-DELETE-LINE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_17')
    dw(['DUP', 'KEY_F10', '=', '?branch', 'PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_18', 'DROP', 'doLIT', 0, 'EDIT-RUNNING', '!', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DHANDLE_2DEKEY_IF_FALSE_18')
    dw(['DROP', 'EDIT-MSG-UNSUP', 'EDIT-MSG', '!', 'EXIT'])
    colon('EDIT-WAIT-INPUT', [])
    label('PC_08_2Deditor_EDIT_2DWAIT_2DINPUT_BEGIN_1')
    dw(['?EKEY', '?branch', 'PC_08_2Deditor_EDIT_2DWAIT_2DINPUT_IF_FALSE_2', 'EDIT-HANDLE-EKEY', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DWAIT_2DINPUT_IF_FALSE_2')
    dw(['?KEY', '?branch', 'PC_08_2Deditor_EDIT_2DWAIT_2DINPUT_IF_FALSE_3', 'EDIT-HANDLE-CHAR', 'EXIT'])
    label('PC_08_2Deditor_EDIT_2DWAIT_2DINPUT_IF_FALSE_3')
    dw(['branch', 'PC_08_2Deditor_EDIT_2DWAIT_2DINPUT_BEGIN_1'])
    dw(['EXIT'])
    colon('EDIT-RUN', [])
    dw(['doLIT', -1, 'EDIT-RUNNING', '!'])
    label('PC_08_2Deditor_EDIT_2DRUN_BEGIN_1')
    dw(['EDIT-RUNNING', '@', '?branch', 'PC_08_2Deditor_EDIT_2DRUN_WHILE_END_2', 'EDIT-REDRAW', 'EDIT-WAIT-INPUT', 'branch', 'PC_08_2Deditor_EDIT_2DRUN_BEGIN_1'])
    label('PC_08_2Deditor_EDIT_2DRUN_WHILE_END_2')
    dw(['NORMAL', 'CURSOR-ON', 'CLS', 'HOME', 'EXIT'])
    colon('EDIT', [])
    dw(['EDIT-INIT', '2DUP', 'EDIT-LOAD', 'DUP', '?branch', 'PC_08_2Deditor_EDIT_IF_FALSE_1', 'EDIT-DONE', 'EXIT'])
    label('PC_08_2Deditor_EDIT_IF_FALSE_1')
    dw(['DROP', 'EDIT-RUN', 'EDIT-DONE', 'doLIT', 0, 'EXIT'])
    colon('NEW-EDIT', [])
    dw(['EDIT-INIT', 'EDIT-PATH!', 'EDIT-NEW', 'EDIT-RUN', 'EDIT-DONE', 'EXIT'])
