#ifndef PDR_VM_CONFIG_H
#define PDR_VM_CONFIG_H

#include <stdint.h>

#define VM_ROM_START 0x0000u
#define VM_ROM_END 0x7FFFu

#define VM_RAM_LOW_START 0x8000u
#define VM_RAM_LOW_WORDS 512u
#define VM_RAM_LOW_END (VM_RAM_LOW_START + VM_RAM_LOW_WORDS - 1u)

#define VM_RAM_HIGH_START 0xF500u
#define VM_RAM_HIGH_WORDS 2816u
#define VM_RAM_HIGH_END 0xFFFFu

#define VM_UPP 0xFE80u
#define VM_SP0_VISIBLE 0xF97Fu
#define VM_RP0_VISIBLE 0xFE7Fu
#define VM_SP_EMPTY VM_SP0_VISIBLE
#define VM_RP_EMPTY VM_RP0_VISIBLE

#define VM_DATA_STACK_WRITE_FLOOR 0xF900u
#define VM_RETURN_STACK_WRITE_FLOOR 0xFE00u

#define VM_COLD_VECTOR 0x0000u
#define VM_BAUD_RATE 115200ul
#define VM_STEP_BUDGET 256u
#define VM_TRACE_STEPS 0
#define VM_SERIAL_RX_TRACE 0
#define VM_SERIAL_PEEK_TRACE 0
#define VM_STACK_TRACE 0

#endif
